### PR TITLE
less2sass

### PR DESCRIPTION
**Pull request by pichalite**

### CODE REVIEW

**Comment by MegaGM** [comment]
dude, nooooo

**Comment by pichalite** [comment]
why not

**Comment by julianlam** [comment]
@MegaGM I like LESS too, although the times are a-changin'... with Bootstrap officially switching their development language to SASS/SCSS (I still don't know the difference) from LESS, in my mind, they've sounded the death knell for LESS itself.

It's not a matter of _if_, but a matter of _when_, and the efforts of @pichalite will significantly speed up our efforts towards proper SASS adoption :smile:

**Comment by julianlam** [comment]
We're currently investigating the feasibility of having LESS and SASS compiled in parallel.

**Comment by MegaGM** [comment]
@julianlam  Ah, okay :(
The most interesting question then is "Will we have to rewrite all the plugins?"

**Comment by pichalite** [comment]
If your plugin has any tpl files using bootstrap classes... you will have to change them anyway as most of them are changed in Bootstrap 4.

**Comment by pichalite** [comment]
will submit again once bs4 hits beta

**Pull request closed without merging**
