### PR TITLE
Ukrainian language translation

### PR DESCRIPTION
**Pull request by mortiy**
I've finally finished Ukrainian translation on Transifex (https://www.transifex.com/nodebb/nodebb/language/uk/).
These files are fetched using Transifex CLI tool.

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled through [our Transifex project](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

----

*This is an automated message. If you feel this action was in error, please comment on this pull request so it can be looked at again*

**Comment by julianlam** [comment]
Thanks @mortiy -- @nodebb-misty actually does this daily, so no need to make a pull request, but thank you! 😄

**Comment by mortiy** [comment]
Thanks @julianlam.
Will it also update `.tx/config`, because Ukrainian currently is not there?

**Comment by julianlam** [comment]
Hi @mortiy -- My apologies... `uk` should be available in NodeBB now :)

**Pull request closed without merging**
