### PR TITLE
German language additions

### PR DESCRIPTION
**Pull request by RohdeK**
Some of the new translations have been missing in the german translation files.

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Pull requests need to be made against either `master` or `develop`. It looks like this pull request was made against a version branch and should not be merged. Please comment if you feel that this is in error.

Thanks!

**Comment by oplik0** [comment]
If you want to edit translations, go to NodeBB transifex project: https://www.transifex.com/nodebb/nodebb/

Changes from there are merged to `master` daily.

And the not also rejects PRs that change translations directly automatically, redirecting users to this transifex project instead, so since you didn't get this message here (different problem that meant automatic close), I'm telling you this so that you don't try a direct PR again just to get the same result :)

**Comment by julianlam** [comment]
He didn't get the message? 😕

**Comment by RohdeK** [comment]
I got the message alright. Will create more translations and submit them
over the named translation tool rather than create a new PR. The PR can be
deleted.

Greetings

Julian Lam <notifications@github.com> schrieb am Fr., 28. Aug. 2020, 18:16:

**Comment by oplik0** [comment]
> 
> 
> He didn't get the message? 😕

This PR was closed due to being made against `1.14.x` branch instead of `master` or `develop`, and that problem was the one mentioned in the @nodebb-misty message, but the message didn't say anything about transifex and not accepting changes to language files via PR.

So instead of
> Hello there! 😄
>
> Our internationalisation project is handled through our Transifex project. Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.
> 
> Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.
> 
> Thank you! 👼

they got:
> Pull requests need to be made against either master or develop. It looks like this pull request was made against a version branch and should not be merged. Please comment if you feel that this is in error.
> 
> Thanks!

**Pull request closed without merging**
