### PR TITLE
make thumb obey image size restrictions.

### PR DESCRIPTION
**Pull request by yariplus**

### CODE REVIEW

**Comment by yariplus** [comment]
Prevent errors on ridiculous thumb values. Probably need to add some client js to min the actual value, and some absolute maximum values based on sharp maximums. Can add those too if you agree.

**Comment by barisusakli** [comment]
This change won't really do anything, `meta.config.rejectImageWidth` is used to reject an image if its too big so we don't waste time resizing it. For example https://github.com/NodeBB/NodeBB/blob/master/src/controllers/uploads.js#L56

**Comment by yariplus** [comment]
Gotcha. This was to prevent an error if thumb size is too large, but it's a poor solution.

Basically, there is no enforced thumb size. If you set to a size higher than sharp supports (65535 i think), it will error out. (coordinates out of range) Kindof a dumb error, but there should be an enforced maximum to prevent it.

I'm not sure why someone would want a 65535px thumb, but we should stop them from entering an arbitrarily large value, like me. Using the max image width was a dirty hack.

I'll come up with a better solution.

**Comment by barisusakli** [comment]
```
await image.resizeImage({
			path: uploadedFile.path,
			width: meta.config.topicThumbSize,
			height: meta.config.topicThumbSize,
			width: Math.min(meta.config.topicThumbSize, meta.config.rejectImageWidth),
			height: Math.min(meta.config.topicThumbSize, meta.config.rejectImageHeight),
		});
```
This code will still try to resize the 100k image down to either `topicThumbSize`(120px) or `rejectImageWidth`(5000px).
Just change to 
```
await image.checkDimensions(uploadedFile.path);
await image.resizeImage({
			path: uploadedFile.path,
			width: meta.config.topicThumbSize,
			height: meta.config.topicThumbSize,
			width: Math.min(meta.config.topicThumbSize, meta.config.rejectImageWidth),
			height: Math.min(meta.config.topicThumbSize, meta.config.rejectImageHeight),
		});
```
Then the image will be rejected if its bigger than `rejectImageWidth/Height`

**Pull request closed without merging**
