### PR TITLE
Use tini in Dockerfile and avoid sh wrapper

### LINKED ISSUE #6106: Docker image will always get stopped with a SIGKILL and potentially leak zombie processes
The node.js process in the docker image will always get stopped with a SIGKILL even on a regular shutdown of the container, and the container will also potentially leak zombie processes.

The reason is that the actual command currently running is: `sh -c ./nodebb start` and 1. `sh` if sent SIGTERM will as far as I know will not forward it to any children (and hence they get killed eventually when the entire process group is stopped) and 2. `sh` is also not a proper init process that handles terminated child processes unexpectedly attached to it properly.

To not run the command wrapped in `sh`, a different syntax needs to be used:
```
CMD [ "./nodebb", "start" ]
```
However, that leaves the init process problem which means every time a subprocess is opened, e.g. also for something as simple as running any terminal command inside node.js there's a risk of zombie processes occurring - this is a generic design issue of docker which exists because the main process launched inside a container runs with PID 1 and therefore is expected to have special handling for terminating child processes like an init process. A common solution for this is a tini wrapper which simply requires adding this:

```
ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
```

(anywhere in the Dockerfile, usually the ENV setting would be put at the top as a visible configurable option and the rest somewhere at the bottom where the RUN command is)

The only downside for `tini` is that the version pinning needs to be updated regularly. Of course it also adds a tiny amount of overhead, but it's written as a lightweight tool specifically for docker images so it's not very big.

- **NodeBB version:** latest in docker image as of 2017-11-22
- **NodeBB git hash:** latest in docker image as of 2017-11-22
- **Database type:** irrelevant since it's a generic deployment issue
- **Database version:** see above
- **Exact steps to cause this issue:**
1. Launch docker container
2. Use docker inspect on the running container id and check for "Cmd" section which shows what was actually executed:
```
            "Cmd": [
                "/bin/sh",
                "-c",
                "./nodebb start"
            ],
```
- **What you expected:** no sh wrapping, and instead an init process wrapper
- **What happened instead:** sh wrapper with culprits as described above

### PR DESCRIPTION
**Pull request by ghost**
Fixes #6106

### CODE REVIEW

**Comment by JonasT** [comment]
Someone check if what I wrote there with the port makes any sense, I am still stuck in the installer for other reasons. Anyway, just because the node image already exposes a port doesn't mean it shouldn't be listed in this Dockerfile again - EXPOSE doesn't really do anything except inform the reader of a Dockerfile which ports the application uses so it makes a lot of sense to repeat all ports verbosely instead of referring to the original node Dockerfile in a comment.

**Comment by JonasT** [comment]
Just for what it's worth, I tested this successfully with a complete install now. It works fine as far as I can tell. (apart from the problem when throwing away & recreating the container as described in #6109 but this is an issue unrelated to the changes here)

**Comment by JonasT** [comment]
I squashed the commits to one so it's a nicer packaged change. Let me know if I should change anything else (or any other feedback really)

**Comment by JonasT** [comment]
@julianlam yes because nothing is automatically wrapped with it. Basically, a user that is aware can use `--init` on docker run, but it remains a user choice most users won't be aware of and also the user can never know if it's necessary (since some images handle this correctly, e.g. by embedding tini or like the phusion base image).

tini is also exactly the solution docker itself uses, so all this does is basically integrate it right into the image so it works correctly even without the user choosing to supply the optional `--init` flag when creating the container.

**Comment by JonasT** [comment]
TL;DRL strictly speaking it's not necessary, but it makes the image safer and more universally usable for all the users to do this right inside the image.

**Comment by julianlam** [comment]
Fine by me, though would like @BenLubar to take a look at this to see whether it's okay.

**Comment by BenLubar** [comment]
This seems fine, but what does it give us that the change to `CMD [ "./nodebb", "start" ]` doesn't give us already?

**Comment by JonasT** [comment]
@BenLubar adding tini will do proper adoption of orphan processes to avoid zombies. The change to `CMD [ "./nodebb", "start" ]` just fixes SIGTERM/SIGHUP not working correctly, it doesn't fix the zombie issue that can occur in docker containers if you spawn subprocesses that themselves spawn subprocesses and leave them orphaned due to something going wrong.

(You can get zombies basically if something unexpected happens with running npm as a subprocess, e.g. NodeBB is shut down without npm being shutdown first or other rare race conditions. This can lead to stuck zombie processes on the host, while tini will always correctly terminate all subprocesses and correctly clean up any sub-sub-processes e.g. started by npm which on their own are for some reason orphaned e.g. by npm crashing. I recommend googling "docker zombie reaping" if you want more info on this.)

**Comment by JonasT** [comment]
@BenLubar I am still waiting on this for adding more comprehensive overhauls in an additional pull request on top (to make the volume work properly, such that if it's empty at launch it'll get filled with the default install etc). Since I think @julianlam is still waiting for a word of you whether to go ahead with this pull request, it'd be good if you could weigh in. Needless to say, I would recommend it's worth adding this to the image, even though it is only relevant for production use - but IMHO it does make a misconfiguration in production much more unlikely with almost zero cost.

**Comment by BenLubar** [comment]
We've been successfully running a modified version of this on WTDWTF.

Here are the modifications:

```
ENV daemon=true

# Disable daemon in the code, but keep daemon enabled in the config so PID works.
RUN sed -e "s/require('daemon')/if (false) &/" -i /usr/src/app/loader.js

# Remove pidfile when the container starts to avoid a restart loop when NodeBB thinks it's already running.
CMD rm -f pidfile && exec ./nodebb start
```

**Comment by pitaj** [comment]
@benlubar isn't that the same as running `node loader.js --no-daemon`?

**Comment by BenLubar** [comment]
@pitaj I want it to think it's a daemon so it can create `pidfile` which will make the `./nodebb` command work, but not to actually run `require('daemon')`, which forks the process and allows `./nodebb start` to return.

**Comment by pitaj** [comment]
hmmmm I thought loader created the pidfile?

**Comment by JonasT** [comment]
Since I don't use NodeBB anymore and I think NodeBB's CLA is quite unusually toxic and harmful, I'll hereby retract this pull request. Maybe it can guide someone to do something similar, but for now I'll stay out of this project

**Pull request closed without merging**
