### PR TITLE
Use the hide class instead of jQuery hide

### PR DESCRIPTION
**Pull request by pitaj**
So it can be overridden by themes more easily

This way, themes can add transitions

### CODE REVIEW

**Comment by julianlam** [comment]
Hm, I believe Bootstrap is moving away from the classes to hide and show, in favour of jQuery's usage. Might impact whether or not this PR is mergable...

**Comment by pitaj** [comment]
@julian wait, what? If they are moving away from using classes to using jQuery, that is stupid. 

I looked it up, in the source it says they're moving away from `hide` to `hidden`

[`Note: Deprecated .hide in favor of .hidden or .sr-only (as appropriate) in v3.0.1`](https://github.com/twbs/bootstrap/blob/e38f066d8c203c3e032da0ff23cd2d6098ee2dd6/less/utilities.less#L26)

**Comment by julianlam** [comment]
If I recall correctly, it has something to do with *better* interop with `jQuery.hide()`/`.show()`, as the latter adds inline style and bootstrap does it with classes...

**Comment by pitaj** [comment]
Well, then just implement the first two commits. That's all that's necessary for the persona changes.

In my opinion, showing and hiding elements, and conditional styling in general, is the domain of CSS classes.

**Comment by barisusakli** [comment]
Update these classes to `hidden` then?

**Comment by pitaj** [comment]
@barisusakli should I do that, or should I rollback and only use the changes necessary for NodeBB/nodebb-theme-persona#171?

**Comment by barisusakli** [comment]
Yeah only do the changes necessary for the other PR.

**Comment by pitaj** [comment]
@barisusakli Alright, everything here and on NodeBB/nodebb-theme-persona#171 should be good. Tested locally, seems to work great.

**Comment by barisusakli** [comment]
This seems to have broke the link to the advanced search page inside the search input :anguished:

**Comment by pitaj** [comment]
@barisusakli Confirmed. Will fix.

**Pull request merged**
