### PR TITLE
ENH: Add Firestore adapter initial setup

### PR DESCRIPTION
**Pull request by NazimHAli**
I initially started working on a different project to build a forum using Firestore as the backend + Firebase auth as the authentication. After reading this post https://community.nodebb.org/topic/15941/google-firestore-dbal/6 and discovering this example PR to add a database adapter, I think we can add Firestore support too.

This is a work in progress, suggestions/contributions welcome. I'm new to this codebase and still don't fully understand the adapter requirements, just going off of the PR mentioned above and other 2 DB source codes. Any help is appreciated!

### CODE REVIEW

**Comment by julianlam** [comment]
@NazimHAli Sorry to hear that using Firestore was not feasible due to cost :cry:

**Comment by NazimHAli** [comment]
> @NazimHAli Sorry to hear that using Firestore was not feasible due to cost cry

It's unfortunate :disappointed:

**Comment by gslender** [comment]
When you say not feasible due to cost - compared to what? What hosting method is considerably better that makes cost not a factor?

**Comment by julianlam** [comment]
The issue is that the cost of running Firestore increases linearly(?) with database size. While you can say the same with any other data store, the fact that Firestore is hosted purely in the cloud makes it cost prohibitive for any but the smallest sites.

**Comment by arnavsharma-goat** [comment]
@NazimHAli , hey, I am implementing Nodebb in an existing project. I have tested all three (Mongo, Redis, and Postgres) using Supabase. I get better write speeds with Mongodb and Redis, and the Firestore change you made. Have you done these? Are they working to connect to Firestore, and if so, what is the speed like? Also, I have cloned the Nodebb repo and hosted it on Render, using its APIS because I have a fully custom UI.

**Pull request closed without merging**
