### PR TITLE
Support package manager: cnpm and pnpm

### PR DESCRIPTION
**Pull request by greenhat616**
* Support package manager: cnpm and pnpm
* use `const` and `let` instead of `var`

Please CLOSE #6427 and #6439, because of my account suspended.

### CODE REVIEW

**Comment by greenhat616** [comment]
Screenshot_20200323-232454
signed

**Comment by greenhat616** [comment]
@julianlam have done.
* store `supportedPackageManager` in default `package.json`
* fix wrong `in` use

**Comment by greenhat616** [comment]
@julianlam You've got me there.
I tried:
```js
// src/cli/index.js
// config export
module.exports = {
	config: {
		supportedPackageManager: [
			'npm',
			'cnpm',
			'pnpm',
			'yarn',
		],
	},
};

if (module.parent) { // if be reqired(used as a module), do not run the cli code
	return;
}
```

But NOT WORK Any more. Any suggestion else?

**Comment by julianlam** [comment]
Ah nevermind, my mistake as that file is not meant to be `require`'d. Can you put it in `package-install.js` then?

**Comment by greenhat616** [comment]
@julianlam have done.

**Comment by greenhat616** [comment]
have any review comment about this PR? thx.

**Pull request merged**
