### PR TITLE
Textcomplete Plugin version bump for mentions

### PR DESCRIPTION
**Pull request by drewdotpro**
Mentions uses TextComplete (shouldn't this library file be in that plugin if that's the only use?) Anyway, I can get Redactor to work with mentions by
a) updating the TextComplete plugin in core
b) updating Redactor to throw a better initialized event
c) updating Mentions to work with Redactor as well

I need TextComplete updated in core (or moved into Mentions plugin) before I can push a proper fix for mentions in Redactor.

### CODE REVIEW

**Comment by drewdotpro** [comment]
This is from the 0.8.0 release:
https://github.com/yuku-t/jquery-textcomplete/blob/v0.8.0/dist/jquery.textcomplete.min.js

**Comment by barisusakli** [comment]
The reasion textcomplete is in core is because its used by mentions and emoji-extended which are both bundled plugins.

**Comment by drewdotpro** [comment]
Okey dokey, thanks for clarification. PR still stands if I'm going to be able to make Redactor "mentions compatible".

**Comment by martyalicante** [comment]
Actually need this too for emojis

**Comment by drewdotpro** [comment]
Still would like this PR taken please.

**Comment by pitaj** [comment]
@barisusakli Do it, mate

**Comment by barisusakli** [comment]
I might have to revert this since it breaks the autocomplete in the default composer

image

Sometimes its placed just out of viewport as well.

**Pull request merged**
