### PR TITLE
place some code under the right loop

### PR DESCRIPTION
**Pull request by voanhcuoc**

### CODE REVIEW

**Comment by pitaj** [comment]
What does this fix?

**Comment by voanhcuoc** [comment]
The conditional code depend on `location` variable, not on `widget`, and should be run once per `location`, not per `widget`

**Comment by pitaj** [comment]
But what does it fix? Is there any actual issue that occurs? I'm thinking that this may not be necessary _at all_ after the widgets refactor @barisusakli

**Comment by voanhcuoc** [comment]
okie, so you guys are going to rewrite it ! Now close.

**Comment by barisusakli** [comment]
@voanhcuoc is right that code can go out of the loop, its not breaking anything since the conditional checks if the area is already added to DOM.

**Pull request merged**
