### PR TITLE
add expiration time to invitations list

### PR DESCRIPTION
**Pull request by yariplus**

### CODE REVIEW

**Comment by yariplus** [comment]
need to add tests, and decide what to display after the invite is accepted.

**Comment by yariplus** [comment]
good

**Comment by julianlam** [comment]
actually, not good.

I'll fix the conflict, but one of the commits is made by `root` on your machine, so I will need to merge them all and commit it for you separately.

**Comment by julianlam** [comment]
I brought your branch up to date with master, but I cannot merge this since it seems incomplete. `expireAt` and expireAtISO` are returned, but there doesn't seem to be handling for actually setting an expiry time? Let me know... I see an invocation of `.pttl()` but that is only called during the controller to load the list of invitations.

Also there doesn't seem to be a place to set an invitation timeout in the modal.

**Review by julianlam — CHANGES_REQUESTED** [review]
:point_up:

**Comment by julianlam** [comment]
Closing as invitations system has been refactored a bit.

**Pull request closed without merging**
