### PR TITLE
fix generated widgets areas glitching on small screens

### PR DESCRIPTION
**Pull request by Alpacatty**
because columns should always be in rows

### CODE REVIEW

**Comment by barisusakli** [comment]
@psychobunny is this good?

**Comment by psychobunny** [comment]
oh yes this is good. and thanks @Alpacatty for the PR. :)

Unfortunately we can't merge this unless you're able to sign a contributor license agreement, please see here:

[Sign CLA](https://www.clahub.com/agreements/NodeBB/NodeBB)
[Official Thread](https://community.nodebb.org/topic/3705/submitting-a-pull-request-to-nodebb-contributor-license-agreement)

**Comment by Alpacatty** [comment]
My pleasure @psychobunny ^_^
(BTW, just wondering, but why is Bootstrap-related code even in Core to begin with? =s)

I tried signing the CLA, but it just gave me a red `We're sorry, but something went wrong.` as a generic 500 error =/ I'll try again later but right now this error just keeps popping up =/

**Comment by Alpacatty** [comment]
CLAHub finally stopped glitching out on me! =D
It should be mergeable now @psychobunny =)

**Pull request merged**
