### PR TITLE
Added support for the HTTP/2 (h2) protocol through 'http2' or 'spdy' node packages

### PR DESCRIPTION
**Pull request by acardinale**
Added support for the HTTP/2 (h2) protocol through the following packages:

- **http2**
https://github.com/molnarg/node-http2

- **spdy**
https://github.com/indutny/node-spdy

Nodebb Http2 support

As with ssl, to enable them, you need to add related information to config.json:

### http2

    {
        "url": "http://127.0.0.1:4567",
        "secret": "8c057569-0c46-4ec3-bb42-0c68106446e5",
        "database": "mongo",
        "port": 4567,
        "mongo": {
            "host": "127.0.0.1",
            "port": "27017",
            "database": "nodebb"
        },
        "http2": {
	     	 "key": "/etc/ssl/test.key",
	     	 "cert": "/etc/ssl/test.crt"
        }
    }

### spdy

    {
        "url": "http://127.0.0.1:4567",
        "secret": "8c057569-0c46-4ec3-bb42-0c68106446e5",
        "database": "mongo",
        "port": 4567,
        "mongo": {
            "host": "127.0.0.1",
            "port": "27017",
            "database": "nodebb"
        },
        "spdy": {
	     	 "key": "/etc/ssl/test.key",
	 	 "cert": "/etc/ssl/test.crt"
         }
    }

Both work, but using HAProxy as load balancer only **spdy** packages works well.
The configs I used for the test are:

### nodebb

    {
        "url": "http://127.0.0.1:4567",
        "secret": "8c057569-0c46-4ec3-bb42-0c68106446e5",
        "database": "mongo",
        "port": 4567,
        "mongo": {
            "host": "127.0.0.1",
            "port": "27017",
            "database": "nodebb"
        },
        "spdy": {
	 	"key": "/etc/ssl/test.key",
	 	"cert": "/etc/ssl/test.crt",
	 	"opts": {
                    "protocol": "h2",
                    "protocols": [ "h2", "spdy/3.1", "spdy/2.1", "http/1.1" ],
                    "x-forwarded-for": true
	 	}
        }
    }

### HAProxy

    global
        #debug
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        pidfile /var/run/haproxy.pid
    
        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private
    
        # Default ciphers to use on SSL-enabled listening sockets.
        ssl-default-bind-options   no-sslv3 no-tls-tickets force-tlsv12
        ssl-default-bind-ciphers   ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    
        spread-checks 4
        tune.maxrewrite 1024
        tune.ssl.default-dh-param 2048
    
    defaults
        mode    http
        balance roundrobin
    
        option  dontlognull
        option  dontlog-normal
        option  redispatch
    
        maxconn 5000
        timeout connect 30s
        timeout client  30s
        timeout server  60s
        timeout queue   30s
        timeout http-request 10s
        timeout http-keep-alive 60s
    
    frontend http-in
        bind *:80
    
        stats enable
        stats refresh 30s
        #stats hide-version
        stats realm Strictly\ Private
        stats auth admin:admin
        stats uri /admin?stats
        
        redirect scheme https if !{ ssl_fc }
        
        default_backend nodes-http
    
    frontend https-in
        mode tcp
        bind *:443 ssl crt /etc/ssl/cert.pem alpn h2,http/1.1
        http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
        use_backend nodes-http2 if { ssl_fc_alpn -i h2 }

        # Websocket? Let's check the http header.
        tcp-request inspect-delay  500ms
        tcp-request content        accept if HTTP
        acl is_websocket hdr(Upgrade) -i WebSocket
        use_backend websocket_backend if is_websocket

        default_backend nodes-http
    
    backend nodes-http
        server node1 172.59.238.121:4567 check ssl verify none
    
    backend nodes-http2
        mode tcp
        http-request add-header X-Forwarded-Proto https
        server node1 172.59.238.121:4567 check ssl verify none

    # All websockets traffic.
    backend websocket_backend
        mode tcp
        option http-server-close
        option forceclose
        no option httpclose
        server server1 172.59.238.121:4567 weight 1 maxconn 8192 check ssl verify none

### CODE REVIEW

**Comment by julianlam** [comment]
@pitaj brought up a good point (offline) about how this is probably a task better suited for nginx or some other reverse proxy to handle.

Unless there's a specific reason for NodeBB to support this, I'm in favour of deferring it to nginx as well.

**Comment by acardinale** [comment]
@julianlam To use nginx means adding an additional layer between HAProxy and NodeBB.

                                      HAProxy
                                /         |          \
                              /           |           \
                           Nginx        Nginx        Nginx   
                         /                |              \
                        /                 |                \
                    NodeBB             NodeBB            NodeBB                 

I maintain the fork

**Comment by pitaj** [comment]
HAProxy supports HTTP/2 as well. You shouldn't need to run nginx or add the
support in Node.

**Comment by acardinale** [comment]
@pitaj could you give me an configuration example?

**Comment by pitaj** [comment]
well with nginx its as easy as adding "http2" after "ssl"

**Pull request closed without merging**
