### PR TITLE
Improved language names

### PR DESCRIPTION
**Pull request by Alpacatty**

### CODE REVIEW

**Comment by julianlam** [comment]
LOL this has got to he a joke, right?

**Comment by ApfelUser** [comment]
Why? Seems legit

**Comment by Firelad97** [comment]
I think `English (Traditional)` should be used, but `English (Simplified)` shouldn't be used, instead it should be `English (US)` or `English (United States)`.

**Comment by psychobunny** [comment]
:trollface:

**Comment by Firelad97** [comment]
:trollface: no

**Comment by ApfelUser** [comment]
l33t m8 :trollface:

**Comment by Firelad97** [comment]
:trollface: NOPE.AVI

**Comment by psychobunny** [comment]
As funny as you guys are, no, we're not going to troll Americans with this PR

Just for the sake of posterity I actually looked this up and there is no such thing, so we're sticking with what we got. Cheers

**Comment by Firelad97** [comment]
Sounds like a good idea. :trollface:

**Comment by ApfelUser** [comment]
:sob: :disappointed: :cry: :crying_cat_face: :sob: :disappointed: :cry: :crying_cat_face: :sob: :disappointed: :cry: :crying_cat_face: NOOOO YOU CAN'T DO THIS TO US! THIS IS L33T M8

**Comment by Firelad97** [comment]
@ApfelUser Sorry you're not going to troll me with this PR :trollface:

**Pull request closed without merging**
