### PR TITLE
Translation mistake

### PR DESCRIPTION
**Pull request by martyalicante**

### CODE REVIEW

**Comment by julianlam** [comment]
Hm, can you make this change on Transifex?

**Comment by martyalicante** [comment]
I did it on transiflex too

**Comment by julianlam** [comment]
Ok, will pull changes from TX later today.

**Comment by martyalicante** [comment]
all right thank you but this pull was for 0.7.x

**Comment by julianlam** [comment]
Should be resolved once we launch v0.7.3 :smile:

**Pull request closed without merging**
