### PR TITLE
add lastonlineISO to user

### PR DESCRIPTION
**Pull request by pichalite**

### CODE REVIEW

**Comment by julianlam** [comment]
Hiya @pichalite , where is this used?

If it's for your theme, can you please supply a companion PR to persona/vanilla? Otherwise it is liable to be accidentally removed due to apparent disuse.

**Comment by pichalite** [comment]
I can send a PR for persona/vanilla. Not sure where you want it. I was planning to add it in the /users/search route for the material theme.

I have seen people asking lastonline time on the /users route in the community.

**Comment by julianlam** [comment]
@psychobunny? :sweet_potato:

**Comment by psychobunny** [comment]
;)

**Comment by psychobunny** [comment]
No need for PR, but if you can style it drop it in we'd appreciate it :)

**Comment by psychobunny** [comment]
Seems legit. I can't merge this from my phone

> Pull requests that have a failing status can’t be merged from a phone.

Even though it's a one line change that doesn't really affect anything, code checks out for me eye test wise...

**Pull request merged**
