### PR TITLE
Add fields for SEO

### PR DESCRIPTION
**Pull request by atomoc**
And adjustments NodeBB for search engines.

### CODE REVIEW

**Comment by atomoc** [comment]
It will work together with the addition in theme (person, lavender, vanila) template `categories.tpl` and `category.tpl`:
```js
    <!-- IF content -->
	<div class="content">
		{content}
	</div>
	<!-- ENDIF content -->
```

**Comment by julianlam** [comment]
Hi @atomoc, I cannot consider merging this pull request because it is far too radical of a change. You will need to break it up into smaller chunks so that it is more easily parsable.

In general, you are adding fields for SEO, but I do not understand why this requires the addition of two (!!) javascript libraries for client-side manipulation, and markdown integration, which has specifically been systematically *removed* from NodeBB core in favour of using the `parse.raw` plugin hook.

The appropriate meta tags for SEO are already added, which is why I do not understand the nature of this PR.

**Comment by atomoc** [comment]
Radical changes are not present, I tried to do everything within the framework of the ideology NodeBB, if you look closely. 

I assumed I was doing wrong in adding new libraries, but do not misunderstand me, I am not a professional NodeJS / NodeBB developer and hope for your support.

> The appropriate meta tags for SEO are already added, which is why I do not understand the nature of this PR.

I tried to significantly improve the SEO structure. If you examine my work you will be able to understand it.

Please, let's finish with my work. Each time, I find it difficult to make merging.

**Comment by atomoc** [comment]
Why closed?

**Pull request closed without merging**
