### PR TITLE
Revamp email templates to be more style agnostic

### PR DESCRIPTION
**Pull request by julianlam**
The header hasn't really aged all that well, and while it looks a lot better than plain text, we ought to have emails that utilise white space a little more effectively. The digest itself is fairly hard to read, and was the focus of the bulk of this work.

New design:

image

### CODE REVIEW

**Comment by julianlam** [comment]
The other templates were all reviewed and standardised:

* Removal of hero image
* Removal of email closing (the "Thanks!`\n\n`{site_title}")
* Additional padding for CTA buttons if present

**Comment by julianlam** [comment]
Active on community.nodebb.org for testing, should see new digest in a couple hours...

**Comment by PostMidnight** [comment]
That's awesome @julianlam . Are there new stings for translations? Will this version support RTL?

**Comment by julianlam** [comment]
There is now

image

**Pull request merged**
