### PR TITLE
A much faster findBootstrapEnvironment method

### PR DESCRIPTION
**Pull request by pitaj**
It might be a little less accurate in cases where the `min-nv-width` variables are overridden, but I think its worth it. People should not be overriding those variables in the first place.

### CODE REVIEW

**Comment by jillesme** [comment]
If we're doing such optimizations why not do this:

``` javascript
function findBootstrapEnvironment2 () {
	return [
  { size: 'md', width: 1200 },
  { size: 'sm', width: 992 },
  { size: 'xs', width: 778 }
  ].reduce(function (prev, curr) {
  	if (window.innerWidth < curr.width) {
    	prev = curr.size;
    }
    return prev;
  }, 'lg');
}
```

**Comment by pitaj** [comment]
@jillesme

I don't see that being any faster and the code looks more complex.

**Comment by pitaj** [comment]
@julian any comment on this?

**Comment by julianlam** [comment]
My main concern is that the original method was written in such a way due to it being future proof. Bootstrap can change all the values they want for xs, sm, etc, and this method won't break.

If the pixel values are hardcoded in, then it doesn't quite work if they're changed in Bootstrap itself.

That, and I have no idea what would happen on different zoom levels...

**Comment by pichalite** [comment]
@julianlam future proof... won't break? You challenged Bootstrap and they accepted the challenge... broken in BS4 :trollface:

**Comment by julianlam** [comment]
@pichalite ha! Didn't see your reply -- yes... it seems like Bootstrap made me quite the fool didn't it...

**Pull request closed without merging**
