### PR TITLE
A small request

### PR DESCRIPTION
**Pull request by atomoc**
Please accept this change, for me is very important. Thank you! :)

### CODE REVIEW

**Comment by julianlam** [comment]
`data.title` is not normally set in the hash, is it? In that case, the addition would be unused and thus cannot be merged...

**Comment by atomoc** [comment]
I use their fields, including and title for categories. What's the problem?

**Comment by atomoc** [comment]
I also use a field **metaDescription** and **content**.

**Comment by atomoc** [comment]
And metaKeywords.

**Comment by julianlam** [comment]
Yes, *you* use the fields, but they are not in core, so this change adds code to core that does nothing at all.

**Comment by julianlam** [comment]
That controller has `filter:category.build`, I would recommend building a plugin to update `title` with the correct value for your template.

**Comment by atomoc** [comment]
Is not it easier to add this field? :)

**Comment by julianlam** [comment]
It is not, because it serves no purpose. We cannot add a field like this, otherwise it will be removed at some later point because it is never referenced.

**Pull request closed without merging**
