### PR TITLE
wrong path

### PR DESCRIPTION
**Pull request by Pappmann**
"Error: ENOENT: no such file or directory, scandir '.../build/public/language'"

### CODE REVIEW

**Comment by pitaj** [comment]
This is the correct path. You need to run `./nodebb build` and you won't shouldn't get that error.

**Comment by Pappmann** [comment]
`./nodebb build` does not help

**Comment by pitaj** [comment]
Does `./nodebb build` fail? It should create a `build/public/languages` directory.

**Comment by Pappmann** [comment]
yes it fail with 

`20/1 19:03:36 [18778] - info: [build] Building language files
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at tryLang (/nodebb/src/meta/languages.js:146:27)
    at /nodebb/src/meta/languages.js:165:11
    at ReadFileContext.callback (/nodebb/src/meta/languages.js:149:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)`

**Comment by pitaj** [comment]
Okay. Can you try pulling latest master and re-running `./nodebb build`?

**Comment by Pappmann** [comment]
Okay Thanks, now it works.

**Pull request closed without merging**
