### PR TITLE
Add user home pages. Fixes #3616

### LINKED ISSUE #3616: [Enhancement] Let user select homepage
Same as admin but on user profiles
captura de pantalla 2015-09-15 a las 23 44 05

### PR DESCRIPTION
**Pull request by yariplus**
Issues:
- I'm repeating the exact same function to grab the default homepages for both the acp and user homepage lists, I'm not sure of the best place to define this function so that both controllers can use it.

- I've seen no ill effects from changing the default routes "categories", "recent", and "popular" to res.redirects, but I didn't change it because I wasn't sure if there was some advantage to using the controller directly.

### CODE REVIEW

**Comment by martyalicante** [comment]
thanks for doing my request, hope it gets accepted but right now seems already conflicts-outdated

**Comment by yariplus** [comment]
Fixed conflict, just waiting on some feedback on the issues I mentioned from devs.

**Comment by julianlam** [comment]
Wow, that's interesting...! Allowing a user to define a home page... good that it is disabled by default.

Is there a companion commit to this PR in the theme repos?

**Comment by yariplus** [comment]
@julianlam It's enabled by default. :) but it is set to 'None'

Not really anything that needs to be changed in the themes, other than the breadcrumb for Home, which should always point to categories and not root as it does now.

**Comment by martyalicante** [comment]
Conflicts again /cry

**Comment by julianlam** [comment]
@yariplus Are you sure? There's no homepage dropdown element in my user settings, so I can't actually select a homepage :smile: 

Unless I'm missing something...

**Comment by yariplus** [comment]
Oh, crap. Looks like I overwrote a bunch when I fixed those merge conflicts. I suck at the gits. ;(

**Comment by yariplus** [comment]
Okay, it should work now.

Added needed theme change.

**Comment by julianlam** [comment]
Cool, checking it out now.

**Comment by julianlam** [comment]
Oh look @yariplus, now you're a contributor to vanilla too :laughing:

**Comment by yariplus** [comment]
whoa :whale:

much amaze

**Pull request merged**
