### PR TITLE
General-Purpose Dockerfile

### PR DESCRIPTION
**Pull request by Alpacatty**
As opposed to the ones in https://github.com/NodeBB/docker-builds, this Dockerfile uses its build context instead of pulling NodeBB from GitHub, which is subjectively superior (though also, from another viewpoint, subjectively inferior) and allows it to just sit in the root of the repository and build whatever version of NodeBB is there without needing to alter the Dockerfile.
(Which would allow the Docker registry to just automagically build an image for the latest commit (or like any other tag) without needing to update the NodeBB/docker-builds repo every time you want a new image to be made... :wink: :wink: :nudge: :nudge: )

All `npm install`ing is handled automagically by dark forces in the [node-onbuild](https://registry.hub.docker.com/_/node/) image, save for the database-specific packages. This is because `node app --setup` is executed at runtime, allowing you to, like, set a database password without publishing it to the public registry.

#### Configuration
Configuration options can be set with the `-e` flag on `docker run`, i.e. `docker run --name nodebb -p 80:4567 --rm -e url=https://community.nodebb.org  -e redis__host=redis.example.com -e redis__password=CorrectHorseBatteryStaple`

#### Plugins & Themes
If you wish to install plugins or themes with this image, there would be two possible ways to go around that:
**1. (the poor man's way)** Add your desired plugins and themes to the `package.json` and do a `docker build`. This will build an image with all the themes and plugins you specified, but will take quite long, as the initial `npm install` and the installation of your plugins are saved as a single layer in Docker's cache, causing every single one of NodeBB's dependencies and NodeBB's dependencies' dependencies and NodeBB's dependencies' dependencies' dependencies to be fetched and installed again, which takes, well, ages.
**2. (the fancypants way)** Simply create the following Dockerfile (assuming the image build from the Dockerfile included in this commit is in the Docker repo as `example/nodebb`) and build it.
```
FROM example/nodebb

RUN npm install nodebb-plugin-imgur \
                nodebb-plugin-stagram \
                nodebb-theme-song

EXPOSE 4566
EXPOSE 4568
```
**Note: you can omit the backslashes and newlines and simply place all of the packages on one line*
***Note 2: depending on how you've got things set up you might want to put the EXPOSE commands before the RUN command, or put every `npm install` in its own RUN*

This example would install two plugins and one theme on top of the regular NodeBB image and exposes two more ports, allowing you to use NodeBB's inbuilt vertical scaling (along with an `-e port=[4566, 4567, 4568]`)
Due to the installation of plugins being on another layer than the initial `npm install`, Docker will just grab the underlying images from its cache and only install the images provided in the RUN command, drastically reducing build time.

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @Alpacatty  -- how does this work with/against https://github.com/NodeBB/docker-builds?

**Comment by julianlam** [comment]
Ping @xaoseric for his thoughts.

**Comment by Alpacatty** [comment]
@julianlam 
* It builds off a widely-used and supported image, so there's less to maintain

* Unlike the image in NodeBB/docker-builds, you don't need to modify this image at all when building an image for a new version of NodeBB. (unless said new version removes `node app --setup` entirely, in which case, the instruction calling `node app --setup` in the Dockefile needs to be removed :stuck_out_tongue: but you get the gist)(Haha get it? GitHub gists? No...? :crying_cat_face: )
* Currently, the workflow for creating a new Docker build is:
  1. Push the changes you made to https://github.com/NodeBB/NodeBB
  2. Note the commit or tag you want to build off
  3. Edit the RUN instructions in the two dockerfiles in https://github.com/NodeBB/docker-build to git clone from that commit or tag
  4. git push those dockerfiles to the NodeBB/docker-build repo
  5. This causes the [Docker Hub Registry](https://registry.hub.docker.com/) to build a new image

  With this Dockerfile sitting in https://github.com/NodeBB/NodeBB, it would become:
  1. Push the changes you made to https://github.com/NodeBB/NodeBB
  2. The [Docker Hub Registry](https://registry.hub.docker.com/) builds a new image

  This will also ensure the `latest` tag of the Docker image in the registry is always built off the actual latest commit and also allows you to get a Docker image based on any arbitrary commit in NodeBB/master by `docker pull`ing the image with its digest.
Fully automating this in the way https://github.com/NodeBB/docker-builds is setup would require you to commit to that repo every time you made a commit to NodeBB/master.

* Unlike https://github.com/NodeBB/docker-builds, it doesn't include a Redis image. This is because the Redis image provided in that repo is just a generic Redis image and doesn't do anything specific to NodeBB, so you can just as well use any Redis image, i.e. [library/redis](https://registry.hub.docker.com/_/redis/) (from the [front page of the registry](https://registry.hub.docker.com/)). No reason NodeBB devs need to maintain their own one.

* NodeBB's setup in this image can be fully automated using the `-e` flag to `docker run`, whereas the one from NodeBB/docker-builds requires you to connect to the image and set everything up yourself.

* The image from NodeBB/docker-builds completely bypasses `loader.js`, so it doesn't have support for NodeBB's native clustering/vertical scaling. This image doesn't bypass `loader.js`.

* This image allows you to easily add plugins and themes to even the most ephemeral of containers. Using "**No. 2. (the fancypants way)**", you can even upload them to the Docker Hub Registry (or any other registry, for that matter) without any sensitive data ever being published.

*(also, I'm not sure how familiar you are with Docker so sorry if you already know this :stuck_out_tongue_closed_eyes: but for those not using Docker this Dockerfile is just an inert text file, so for non-Docker-users merging this commit would add no overhead save a few bytes of text to be downloaded when initially pulling NodeBB)*

**Comment by faddat** [comment]
+1 @Alpacatty 

This is the way to go.  

If nodebb plugins are stored in a folder, it would be possible to store them in a volume, meaning that the application could be upgraded for a version change or whatever, and then the plugins and setting joyously returned to it.  

Should also be possible to have one instance running connected to several databases in order to share system resources.

**Comment by Alpacatty** [comment]
@faddat you can safely store nodebb plugins in a folder in a container using data volumes (see the [Docker User Guide](https://docs.docker.com/userguide/dockervolumes/)). Just mount one on `/usr/src/app/` and you should be fine :grin:

Because in my setup containers are frequently redeployed across machines I chose not to do so, because syncing data can be kind of a hassle. If you only care about point **1)** and not point **2)**, you could handle application upgrades and plugin persistence like this:

Pre-upgrade:
```
FROM nodebb/nodebb:0.7.1

RUN npm install nodebb-plugin-imgur \
                nodebb-plugin-shoutbox \
                nodebb-theme-example
```
Post-upgrade:
```
FROM nodebb/nodebb:0.8

RUN npm install nodebb-plugin-imgur \
                nodebb-plugin-shoutbox \
                nodebb-theme-example
```

And all plugins will still be there! :grinning: 

Note that if you aren't using data volumes, it's not a good idea to store uploads locally, since they'll be wiped when the container restarts. This is also true for [NodeBB/docker-builds](https://github.com/NodeBB/docker-builds).

**Comment by faddat** [comment]
@Alpacatty 

I think I will need to go with the "plugins in a volume" approach because the project I'm working on is more aimed at people who would self-administer their applications.  

On a very general note, I have a good deal of cloud-age that I'd be thrilled to hear that people would like to deploy to in order to test their applications.  I cannot promise stability or anything, as it's a new topology, but I could certainly use help in testing the thing out-- so, if anyone's got dockerized apps that they want to test, give a shout-- I certainly need the feedback for the project :).

**Comment by Alpacatty** [comment]
@faddat Oh sorry, I forgot to answer your "several databases" question :persevere: 
With databases you can do whatever NodeBB can, you just need to pass the config in env variable format to `docker run` rather than json in a file. (i.e. `-e database=mongo -e mongo__host=mongodb.example.com -e redis__password=CorrectHorseBatteryStaple`)

Oh, and if you want to get real fancy you can combine [Volume Containers](https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container) with the [Ambassador pattern](https://docs.docker.com/articles/ambassador_pattern_linking/) :smiley: 
If I recall correctly calls to `require()` are cached and idempotent, so I think you could theoretically just mount `/usr/src/app/node_modules` to a remote volume container and everything should work? Though I've never tried such a thing or done any benchmarking for it >_<
You could do the same for uploads, though you may have to do some routing black magic with that as serving files from a remote machine probably won't be too fast? Though the "I've never benchmarked that" still applies here.

**Comment by Alpacatty** [comment]
So I just realised that NodeBB also needs ImageMagick, but luckily it's already included upstream in the image.
(this Dockerfile builds off `node:0.10-onbuild` which builds off `node:0.10` which builds up `buildpack-deps:jessie` which includes ImageMagick)

**Comment by faddat** [comment]
Actually,

I think I would like to talk with you....

My skype is faddat ,

e-mail is faddat@gmail.com

happy to install whatever so we can chat.

Thanks!
-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +86 186-2612-6079

**Comment by faddat** [comment]
I do hope that we are able to merge this thing-- it's a good deal better than what is currently at Docker hub, and more standards compliant, too.

**Comment by barisusakli** [comment]
@julianlam can we merge this?

**Comment by julianlam** [comment]
I don't think this PR is meant to be merged?

**Comment by faddat** [comment]
I'd like to toss in my $.02 on this:

If you don't merge this one, please merge something like it.  Once you have
a Dockerfile in your repo, your app will become much easier to deploy on
many platforms & systems.

$.02 tossed.

-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by julianlam** [comment]
2¢ much appreciated :smile:

My main worry is that if we add a dockerfile to the repo, we won't be able to maintain it, as we do not use docker regularly.

**Comment by Alpacatty** [comment]
@julianlam one of the main reasons I made this Dockerfile was because frankly, [NodeBB/docker-builds](https://github.com/NodeBB/docker-builds) unmaintained and terrible, so I designed this to be fairly low-maintenance.

Basically, this Dockerfile will "just work" >= 0.7.0 and only needs to be updated when:
* the minimum version of NodeJS that's required changes,
* the CLI commands for setting up and starting NodeBB change or
* the port NodeBB runs on by default changes

If you would like someone to help maintain it anyway and/or set up automated builds with this Dockerfile, I'd be happy to help, as I am currently using this in production on a site with a few hundred users.

**Comment by julianlam** [comment]
> If you would like someone to help maintain it anyway and/or set up automated builds with this Dockerfile, I'd be happy to help, as I am currently using this in production on a site with a few hundred users.

That works for me :smile:

**Comment by julianlam** [comment]
No node 0.12 support? :laughing:

**Comment by Alpacatty** [comment]
> No node 0.12 support? :laughing:

New things are the devil!
Actually though, I just haven't tried it yet. Production was chugging along nicely on 0.10 and personal dev stuff was all on iojs, so I've been holding off until the merger of iojs and node is complete.

Switching this over from 0.10 to 0.12 should be as trivial as replacing `0.10` with `0.12` on the first line though, but haven't personally tested it yet.

**Comment by julianlam** [comment]
Mergeable Baris

**Comment by xaoseric** [comment]
This is defiantly the way to go. just need @julianlam to give permissions to this repo so i can update docker hub for the automated build.

**Comment by julianlam** [comment]
What permissions do you need?

**Comment by xaoseric** [comment]
Read permissions should work

**Comment by Alpacatty** [comment]
While we're at it, actually implementing NodeBB/docker-builds#4 would be nice. I mean, generally it's pretty useful to be able to pull a specific version and actually know what version you're pulling.

**Comment by faddat** [comment]
The catty alpaca speaks truth.

Sent from my ASUS

-------- Original Message --------

**Comment by skylve** [comment]
Any idea when this is gonna be in Docker hub ? (nodebb/nodebb or nodebb/docker)

**Comment by julianlam** [comment]
@xaoseric Who needs read permissions? AFAIK anyone can read this repo... so perhaps I'm missing something.

**Comment by faddat** [comment]
He needs permissions to read the web hooks, so that the bills can be
automated. Then again, I recently saw that you can use the RSS feed of
changes to the repository to base the automated builds from, however if he
has access to the web hooks then the whole thing will just look much more
professional.

**Comment by julianlam** [comment]
Right, let me know the webhook url, and I'll add that in.

**Comment by nesukun** [comment]
^^^ Any updates on this? Also, a bit of documentation on the new docker workflow would be really nice. I'd PR it myself but I don't think I have the required knowledge about the subject to collaborate on that.

**Comment by edasque** [comment]
You can also use this, https://github.com/edasque/docker-nodebb

**Pull request merged**
