### PR TITLE
Add privilege for accessing user information

### PR DESCRIPTION
**Pull request by oplik0**
I started creating this mostly to address #7804 - but I also noticed that removing this page from moderator permissions, and making it require a separate privilege is also a part of #5736.

This pull request adds view:users:info global privilege, that allows user to access /info page of any given user and see their IP address in post tools.
It is given to global moderators by default on installation.

This change requires additional string to translate however: `view-users-info` in `admin/privileges.json`

### CODE REVIEW

**Comment by barisusakli** [comment]
If I am not mistaken, with this change moderators will no longer be able to see the user info page and user IP address until an administrator gives them the view:users:info privilege.

**Comment by oplik0** [comment]
Yup. That's the point - to change it to a separate privilege from moderate, so you can restrict access to global user information to moderators of specific categories. As saesrpg wrote in the #7804 some people for example run a community website where a lot of people are gonna have moderation privileges only for a specific category, and they shouldn't just get access to user information globally. 

And this would continue with the trend of splitting moderation privileges, so you can have more control over them.

**Comment by pitaj** [comment]
I think the concern is that this will essentially be a breaking change unless there's an upgrade script to give existing moderators the privilege so as to not remove the function from people who had it.

**Comment by barisusakli** [comment]
Yeah, just need a upgrade script to give all the current moderators `view:users:info` privilege so we maintain the current functionality, users can remove it afterwards.

**Comment by oplik0** [comment]
I added the upgrade script. However I wasn't sure which folder to add it to, so it went to 1.12.3 as it already was there and it's the closest version to current 1.12.2.

**Comment by oplik0** [comment]
`src/socket.io/posts/tools.js` changed to use async/await instead of callbacks after I originally created this pull request and it created a conflict. Now it's fixed here :)

**Comment by barisusakli** [comment]
Hi @oplik0 should this be added here as well https://github.com/NodeBB/NodeBB/blob/master/src/socket.io/modules.js#L282?

Chat messages also have ip address stored in them and only admins and global mods can see it right now.

**Comment by oplik0** [comment]
Thanks, added it here. Took me some time to realize that weather or not the info bubble is shown is actually handled by the theme and I can't do anything about it (I hoped the tooltip was some theme-independent JS), so I just added `canViewInfo` to data sent to the rendering engine. So after 1.13 is live themes might change `isAdminOrGlobalMod` there (`templates/partials/chats/message.tpl` in persona at least. I'll probably create a pull request with it there then).

I also noticed that IPs were actually displayed for moderators on user profile pages, but simply hidden (at least on persona theme) with css. Fixed this too - now they are only sent to rendering engine if user is administrator, self or has the view:users:info privilege.

**Pull request merged**
