### PR TITLE
Seo 0.5.7

### PR DESCRIPTION
**Pull request by baerrus**
Changes required in nodeBB core to support static pagination and other SEO related features. Server side generated pagination using plain HTML tags. This requires no JS and is friendly to search engines as they do not execute JS when parsing web pages. These changes should cause no visible modification of behavior unless a SEO Theme is installed.

The pagination itself is implemented in a lavender derived theme (see below). I will submit a pull request for that too. As I believe, all those changes can be part of Lavender theme. They all focus on improving SEO and not visual design of Lavender Theme.
See https://github.com/baerrus/nodebb-theme-lavender/tree/seo-nodebb-0.5.7

### CODE REVIEW

**Comment by psychobunny** [comment]
I didn't get a chance to go through the commits yet but on quick glance please follow our coding guidelines as documented here: https://docs.nodebb.org/en/latest/contributing/style-guide.html

Thank you though :)

**Comment by baerrus** [comment]
Sure, what is the problem with style? is it indentation?

**Comment by psychobunny** [comment]
we follow 1tbs ie:

```
if (condition) {
    one();
} else {
    two();
}
```

current PR is

```
if (condition) 
    one();
else
    two();
```

**Comment by baerrus** [comment]
Ok, no problem

**Comment by psychobunny** [comment]
https://github.com/baerrus/nodebb-theme-lavender/commit/14030c841aa25edb4d11fcdeea1c122058d1713d

Good call. Feel free to submit PR, although visually, maybe the CSS should reduce the H2 font size *just a bit* to match current design

**Comment by baerrus** [comment]
Agree H2 text size can be slightly reduced. Submitted PR for the lavender SEO theme. Also fixed styling

**Comment by baerrus** [comment]
@psychobunny I missed that I needed to sign CLA. done

**Comment by psychobunny** [comment]
@baerrus I'm sorry about the delay on merging this PR. I know you've encountered our CLA already before we made it public, but we haven't made it official until today, after having our lawyers look at it. You'll have to re-accept the agreement, if you still are interested. The link is [here](https://www.clahub.com/agreements/NodeBB/NodeBB)

We have a bit of a backlog of PR's that we have to look into, I'll make sure this is a priority for me. Thanks again for the PR :)

**Comment by baerrus** [comment]
@psychobunny Thanks for communicating. Will do CLA again, no worries. I wanted to simplify the change for you down to just 4 commits, so you could just merge it clean. But was a bit slammed like yourself - January effect :).  Will do in the next 1-2 days.

**Comment by barisusakli** [comment]
What is the difference between the pagination code in the topic controller and category controller? Can that code be moved out to a pagination module so it's not repeated?

**Comment by baerrus** [comment]
It can be consolidated. I wasn't too familiar with the codebase. Did not know where to put it.

**Comment by barisusakli** [comment]
No problem, I am working on this right now. Will make a commit today hopefully.

**Comment by baerrus** [comment]
I tried to do CLA again but clahub is giving me an error "We're sorry, but something went wrong."

**Pull request closed without merging**
