### PR TITLE
allow filtering /unread to only topics that have not yet been seen

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by julianlam** [comment]
:shipit:

**Comment by BenLubar** [comment]
Oh, I think my automated update cronjob deleted the branch. I'll go stop that.

**Comment by BenLubar** [comment]
@julianlam is there a way to re-submit a build to travis? It looks like two of them failed before it even looked at NodeBB's code.

**Comment by julianlam** [comment]
I'll probably have to manually do it, as I have access to TravisCI

**Comment by julianlam** [comment]
Restarted the test now...

**Comment by julianlam** [comment]
Hmm... changing function signatures means our next version should be v2.0.0 :laughing: 

Also, I'm not sure whether `?unseen=1` is the best way to do it... perhaps `?filter=new`? Then we could possibly extend it to do things like `?filter=replied`, etc...

**Comment by BenLubar** [comment]
The signature isn't changed unless someone's replacing the function from a plugin. It handles the new parameter being missing.

**Comment by barisusakli** [comment]
Right now you have manually type the url to switch to this view?

Also this won't work with infinite scroll at the moment since the `unseen` query param won't be passed to the server when the user scrolls down.

**Comment by BenLubar** [comment]
Sounds like I need to rewrite this.

**Comment by BenLubar** [comment]
image
image

**Comment by psychobunny** [comment]
Neat

**Pull request closed without merging**
