### PR TITLE
Fix /apple-touch-icon not sending uploaded file

### PR DESCRIPTION
**Pull request by madarche**
This fixes the following error:

$ wget https://nodebb.yourdomain/apple-touch-icon

28/6 09:57:06 [28332] - error: /apple-touch-icon
 Error: ENOENT: no such file or directory, stat '/home/sweet/nodebb/public/assets/uploads/system/touchicon-orig.png'
    at Error (native)

### CODE REVIEW

**Comment by madarche** [comment]
This PR is interesting for the v1.5.x branch which is affected by this error too.

**Comment by barisusakli** [comment]
Looks like everything needs this `.replace(/assets\/uploads/, 'uploads');` I see the same code in the favicon handler.

**Comment by madarche** [comment]
Yes this is the same code than in the favicon handler.

**Comment by barisusakli** [comment]
LGTM

**Comment by madarche** [comment]
Cool 😊

**Pull request merged**
