### PR TITLE
Use new form issue templates

### PR DESCRIPTION
**Pull request by oplik0**
GitHub added a new type of issue templates some time ago, which essentially allow one to create a custom issue forms instead of just being the default issue text.
I wanted to experiment a bit with them and ended up converting the NodeBB issue template to the new format :)

This adds two templates (bug report and feature request) and links to community forum and bug bounty page (sadly, you can't add mailto in contact links), while still allowing a fallback to standard issue form.

You can see how it looks and experiment with it here: https://github.com/oplik0/github-templates-experiments/issues/new/choose
I don't mind having a few more open issues there :V

Questions/notes:
1. I took the liberty to add ` Anything else?` at the end of bug report form, since I think in this more constricted format it's a good idea to have a clear place for things that don't fit the other fields, but I can obviously remove it if it's not needed
2. I added default labels to the templates, `bug` and `needs confirmation` to bug reports and `enhancement` to feature requests. Are these okay or should I leave feature requests labelless?
3. Feature request is a very minimal form added mainly because the `Open a blank issue` link is so small :) So I put just the description and optional link to community forum there. I welcome any other ideas though.
4. Bug requests don't actually require any fields at this point. Is there any one that would be considered essential to all reports? NodeBB version perhaps?
5. I also allowed selection of multiple databases for cases where more than one is affected.
6. As mentioned before it's still possible to create a blank issue, but if GitHub is only supposed to track bugs and feature requests perhaps it's not necessary?
7. On similar note, I deleted the current `ISSUE_TEMPLATE.md`. It'd still be used for blank issues, but if they're just a fallback I don't think it's necessary? I can restore it if anyone will miss it though :)

This PR is for `master` branch since community health files only work there anyway, and it doesn't actually affect NodeBB itself.

### CODE REVIEW

**Comment by julianlam** [comment]
The only thing I'd point out is that we tend to use the bug and enhancement labels only when a bug is confirmed or if the feature request is approved.

Might be we would want a "needs confirmation" label on all for now.

**Comment by julianlam** [comment]
Any issues tagged with the needs confirmation, or needs more info, labels are automatically closed by Misty after 14 days.

If we do merge this pr, we would have to adjust that behaviour.

**Comment by julianlam** [comment]
> If the desired behavior is "no labels = no one looked at the issue"

That's just how it works right now, but there's no reason we can't change... or try to, anyhow :smile:

**Comment by oplik0** [comment]
Personally I like categorization of issue type being separate from status, so if there is flexibility on that front I'd say that having `enhancement`/`bug` labels by default and separate `confirmed` (or something similar) label as the equivalent of current acknowledgement with one of the type labels would be a bit clearer.

Especially with the new `close as not planned`, since it removes the need for a label for that situation.

The current Misty setup where `needs confirmation`/`needs more info` are applied only when the original issue isn't enough could be left as is then.

**Comment by julianlam** [comment]
That could work. Outside of its use as an indicator of "has been looked at", the only other way we use it is as a filter for issues, when manually creating a list of notable features (for blog posts and such).

Instead of labelling an issue as an indicator that it's "confirmed", we could milestone the issue. In fact, we already do that, so this wouldn't be much of a change for us.

**Pull request merged**
