### PR TITLE
add callback to refreshTitle

### PR DESCRIPTION
**Pull request by akhoury**
related to #4113 - we really need to start using promises, or bring the `async` lib to the client-side

### CODE REVIEW

**Comment by akhoury** [comment]
i dont know .. i dont like keep nesting callbacks but it didn't seem like async is loaded on the client-side - and not sure if you want to start using promises or not.

**Comment by barisusakli** [comment]
I think this still doesn't solve the problem because of the 2000 setTimeout in alternating title.

https://github.com/NodeBB/NodeBB/blob/master/public/src/app.js#L311

**Comment by akhoury** [comment]
true, but only if  the [alternatingTitle `title.length > 0`](https://github.com/NodeBB/NodeBB/blob/master/public/src/app.js#L294)

but yea, that's getting complicated. feel free to close and fix differently, I dont have a strong opinion about this :P

**Comment by barisusakli** [comment]
Would a new hook help that gets fired when the title changes? What are you trying to do?

**Comment by akhoury** [comment]
well, im trying to use `ajaxify:end` event to fire a pageView-like event, to an analytics system, but it does require the `document.title` - I mean, honestly, I feel like the `document.title` should be updated by that time, except that it's async. Creating a new hook won't help as much since the document.title might get updated even if there is `ajaxify:end` event, i.e. when a chat message is received.

**Comment by barisusakli** [comment]
What if we pass the new title to ajaxify.end as a parameter? I think it only has url right now.

**Comment by akhoury** [comment]
> What if we pass the new title to ajaxify.end as a parameter

that works - and probably the best idea.

**Pull request closed without merging**
