### PR TITLE
Redirect incorrect slugs instead of 404

### PR DESCRIPTION
**Pull request by FokkeZB**
If you rename the title of a category or topic you want shared links to remain working and not 404

### CODE REVIEW

**Comment by julianlam** [comment]
This is a delicate matter with no confirmed resolution. We made the decision early on to return a 404 if a slug is specified incorrectly when navigating to a topic. This is obviously not ideal, as since the `tid` is in the url itself, there is no real need to validate the slug **at all**.

However, this presented an issue where someone could compose a post with images of this syntax:

`;  ;`

... and the browser would blindly load the following urls:

* `/topic/123/a`
* `/topic/123/b`
* `/topic/123/c`

Without the 404, this would cause the server to load the same topic three times (four, if you count the initial topic load), with those three loads being essentially useless because the browser then tries to parse the returned HTML as an image, fails, and displays the "broken image" picture.

So best case scenario, it ties up resources, worst case scenario, someone could construct a post that if you navigate to it, DoS's your server.

**Comment by julianlam** [comment]
Now, that said... you bringing this up again has gotten me thinking about alternative ways to handle this, so I'll get back to you.

**Comment by FokkeZB** [comment]
@julianlam can you explain how the changes to the markdown plugin fix close this issue?

**Comment by julianlam** [comment]
@FokkeZB The plugin, with changes, would look at relative URLs and not parse them if they don't point to an image in the uploads folder. 

The other half should be done in core, to not check the slug... one moment.

**Comment by julianlam** [comment]
@FokkeZB There you go :smile:

**Comment by FokkeZB** [comment]
That URL check also works when you use an image upload plugin like Amazon S3?

**Comment by julianlam** [comment]
@FokkeZB, yes, absolute urls are unaffected

**Comment by FokkeZB** [comment]
Including those starting with `//` ?

**Comment by julianlam** [comment]
Should be handled, give it a try.

**Pull request closed without merging**
