### PR TITLE
feat: more discrete commit-on-save instead of commit-on-change w/ confirm modals

### PR DESCRIPTION
**Pull request by julianlam**
*Small UI hints when privileges changes are staged (but not committed/saved)*
image

*New save/discard buttons*
image

### CODE REVIEW

**Comment by julianlam** [comment]
image

A better view of the new privilege setting hints... green check for staged addition, red outline for staged removal, and red dash for staged removal (but indeterminate privilege still applies)

**Comment by pitaj** [comment]
So what's the difference between the types of staged removal?

**Comment by julianlam** [comment]
Nothing, it simply denotes the privilege that will be set or removed, once you hit save.

**Comment by pitaj** [comment]
Wait now I'm more confused. Why are there two types of staged removal?

**Comment by julianlam** [comment]
There aren't. It's just showing that it's an inherited privilege, so removing it won't do anything.

**Comment by julianlam** [comment]
Was out when you commented... basically, there are two kinds of privileges, same as before. Either it's applied, or not. However, we added the inherited privilege just as a way to explain to admins that because `registered-users` has a certain privilege, then basically all users have that privilege, since all users are members of `registered-users`.

So that's why we use the indeterminate checkbox state; the dashed input.

The new colouring simply signals to the admin that the changes have not been applied yet, that is all :smile:

**Pull request merged**
