### PR TITLE
Make ACP sidebar fixed

### PR DESCRIPTION
**Pull request by pitaj**
If you want to implement some kind of replacement for the CSS calc I
used, go ahead and do it yourself. I'm hoping webmasters can either deal
with a tad bit of overlap or have a modern browser.

### CODE REVIEW

**Comment by pitaj** [comment]
Fixes #2696

**Comment by psychobunny** [comment]
Hmmmm I think it would have been better to use BS Affix component?

**Comment by pitaj** [comment]
Affix is meant to handle sidebars when the position changes on the screen when it is scrolled down. The position of these sidebars is not changed when the window is scrolled, they keep the same relative position to the top bar. Affix isn't necessary in this case.

**Comment by pitaj** [comment]
If you can think of a reason to use it, I'll gladly do so, but for now, it isn't worth it as far as I can see.

**Comment by psychobunny** [comment]
Gotcha. Looks good to me, except when the width is smaller:

**Comment by pitaj** [comment]
Fixed it in a583f9d77adf1e666cc6bd56e82a51ff3a2e83c3

Should be good to go now

**Comment by barisusakli** [comment]
image

Is what happens on events page, /logs works so not sure why its only that page.

**Comment by pitaj** [comment]
I'll take a look at it tomorrow.

**Comment by pitaj** [comment]
https://github.com/NodeBB/NodeBB/pull/2736 

Fixed that problem @barisusakli

**Pull request merged**
