### PR TITLE
Fix accidental clobbering of package.json values on merge

### PR DESCRIPTION
**Pull request by julianlam**
- fix: use fs.promises
- fix: #10229, package merging should deep merge nested objects

### CODE REVIEW

**Comment by pitaj** [comment]
It appears this doesn't address the concern I had with old devDependencies saying around

**Comment by julianlam** [comment]
Correct, the behaviour has not changed. What was the issue with dev deps?

**Comment by pitaj** [comment]
With the old behavior, devDeps were replaced entirely. So if we removed a devDep in install/package.json, it would be removed during the package upgrade step. With these changes, removed devDeps will be left behind, potentially accumulating over time.

**Comment by julianlam** [comment]
Right. We can treat `devDependencies` like `dependencies` as well 👍

Will need to add a failing test to be certain.

**Pull request merged**
