### PR TITLE
TS 

### PR DESCRIPTION
**Pull request by bhavya3024**

### CODE REVIEW

**Comment by nodebb-misty** [comment]
## 💡 Friendly Note

This pull request was made against the `develop` branch, which is reserved for commits destined for a **minor** or **major** release.If your commits simply fixes a bug, please rebase this PR against the `master` instead.

* **patch** releases — bug fixes only
* **minor** releases — new features, enhancements, and bug fixes
* **major** releases — breaking changes, including all of the above

Thanks!

**Comment by bhavya3024** [comment]
@pitaj check the first commit, it is showing the changes as required (as renames). But not having with 2 commits!
https://github.com/NodeBB/NodeBB/pull/11087/commits/5f35a94ebce1b0abf17e4d6782724e7e4cea7855

**Comment by bhavya3024** [comment]
> nodebb@3.0.0-alpha.1 build
> rm -rf build && tsc && node ./copy-non-ts-files.js

SERIOUSLY?
META ->> undefined
/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/cache.js:12
    maxSize: meta_1.default.config.postCacheSize,
                            ^

TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/cache.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/parse.js:24:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

@pitaj @julianlam Now I seriously need your help resolving this issue at all!. I am stuck! Use github desktop to see my changes as renames!

**Comment by pitaj** [comment]
> check the first commit, it is showing the changes as required (as renames). But not having with 2 commits!
> [5f35a94](https://github.com/NodeBB/NodeBB/commit/5f35a94ebce1b0abf17e4d6782724e7e4cea7855)
> If the changes are very severe, it won't show as renames explained here: https://stackoverflow.com/questions/433111/how-to-make-git-mark-a-deleted-and-a-new-file-as-a-file-move

Maybe I'm not finding the right "first commit", but everything I've seen - including the one you linked - contains more than just renames from .js to .ts

I don't know how much more clear I can be: 

- the first commit should contain ONLY file renames
- ALL file renames should be conducted using `git mv`
- ALL files renames should be done in that first commit

Put any other changes in subsequent commits.

**Comment by bhavya3024** [comment]
> > check the first commit, it is showing the changes as required (as renames). But not having with 2 commits!
> > [5f35a94](https://github.com/NodeBB/NodeBB/commit/5f35a94ebce1b0abf17e4d6782724e7e4cea7855)
> > If the changes are very severe, it won't show as renames explained here: https://stackoverflow.com/questions/433111/how-to-make-git-mark-a-deleted-and-a-new-file-as-a-file-move
> 
> Maybe I'm not finding the right "first commit", but everything I've seen - including the one you linked - contains more than just renames from .js to .ts
> 
> I don't know how much more clear I can be:
> 
> * the first commit should contain ONLY file renames
> * ALL file renames should be conducted using `git mv`
> * ALL files renames should be done in that first commit
> 
> Put any other changes in subsequent commits.

@pitaj Done specifically as requsted, now please check!!

**Comment by pitaj** [comment]
Great! I can see that even with the renames separated the normal diff will show everything as changed.

But that's okay, because we can just exclude that commit when looking at the diff.

Going forward, I'd recommend keeping your commits granular rather than force pushing.

Thanks 👍

**Comment by bhavya3024** [comment]
@pitaj I am stuck here while doing `./nodebb build`:  
```
x2022-12-25T18:27:31.811Z [4567/88428] - error: uncaughtException: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/cache.js:11:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/parse.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {"date":"Sun Dec 25 2022 23:57:31 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[4.92578125,4.0302734375,3.8720703125],"uptime":540295},"process":{"argv":["/Users/bhavya.dhiman/.nvm/versions/node/v14.21.2/bin/node","/Users/bhavya.dhiman/Documents/NodeBB/nodebb","build"],"cwd":"/Users/bhavya.dhiman/Documents/NodeBB","execPath":"/Users/bhavya.dhiman/.nvm/versions/node/v14.21.2/bin/node","gid":20,"memoryUsage":{"arrayBuffers":2588253,"external":5409914,"heapTotal":61370368,"heapUsed":42261008,"rss":119848960},"pid":88428,"uid":502,"version":"v14.21.2"},"stack":"TypeError: Cannot read property 'config' of undefined\n    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/cache.js:11:29)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/parse.js:28:33)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","trace":[{"column":29,"file":"/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/cache.js","function":null,"line":11,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1085,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1114,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":950,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":790,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":974,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":101,"method":null,"native":false},{"column":33,"file":"/Users/bhavya.dhiman/Documents/NodeBB/build/src/posts/parse.js","function":null,"line":28,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1085,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1114,"method":".js","native":false}]}
```
Dont know what's wrong in the meta file itself, the `src/meta/index.ts` file gets stuck in the import process and after subsequent imports in other files, it just calls the  `src/posts/cache.ts`  and it calls meta from import and results undefined.

**Comment by pitaj** [comment]
Alright, I've looked at what you've done, and I'm afraid I'm going to have to ask you to essentially restart again. I sincerely appreciate your effort, but what you have so far is quite heavy handed. Here are my detailed thoughts:

You won't be able to know if you've messed things up if you can't even get past the early startup stages. First of all, you'll need to keep around a few important JS files so our `npm install` bootstrapping process stays possible. This includes the [early parts of `src/cli/index.js`](https://github.com/NodeBB/NodeBB/blob/cf7aa19419cdc21935ed8e6ee2ef9010e9905a61/src/cli/index.js#L5-L59) (I recommend pulling that out into it's own file `src/cli/bootstrap.js` which calls into `build/src/cli`), `package-install.js`, `constants.js`, and `require-main.js`. I've made those changes myself [here](https://github.com/bhavya3024/NodeBB/compare/ts...NodeBB:NodeBB:pitaj-ts) while trying to get your version running locally. You'll notice I added a naive typescript transpilation to the bootstrap code there. This way things can continue to work as normal, and we can work out architectural changes later.

You've also made a lot of sweeping changes all at once. One example is changing all `process` to `process as any`. That's just not the way to go about changes like this. I'd not that important that everything passes typechecking right away - it's far more important that you keep things working and passing tests so you can detect when you broke something irreparably.

Instead, work through each module one at a time. I'd recommend starting with `cli` and working your way out from there to `meta`, `upgrades`, etc. It's okay to have some `require` calls left in there if you can't get things to work without them - we can assist with taking care of the edge cases at a later time.

I also noticed you aren't really converting modules to ESM as is customary. Converting a module to ESM should pretty much never result in exporting an object like so:

```ts
// src/api/index.ts

import users from './users';
import groups from './groups';
import topics from './topics';
import posts from './posts';
import chats from './chats';
import categories from './categories';
import flags from './flags';

export default {
	users,
	groups,
	topics,
	posts,
	chats,
	categories,
	flags,
};
```

Instead, each of those should be exported as a separate item:
```ts
export * as users from './users';
export * as groups from './groups';
export * as topics from './topics';
export * as posts from './posts';
export * as chats from './chats';
export * as categories from './categories';
export * as flags from './flags';
```

Another example:

```ts
// src/api/users.ts

const usersAPI = {} as any;

usersAPI.create = ...;
usersAPI.update = ...;
// ...
usersAPI.changePicture = ...;
usersAPI.generateExport = ...;

export default usersAPI;

// DO THIS INSTEAD

export const create = ...;
export const update = ...;
// ...
export const changePicture = ...;
export const generateExport = ...;
```

Finally, I'd like you to split each phase of changes into a separate commit. Avoid force-pushes completely. Split each module you convert to ESM, each module you fix typings for, etc into a separate commit.

**Comment by pitaj** [comment]
BTW, here's a tip for avoiding the issues with `global.env` etc. You can extend the interfaces instead of casting to any.

Here's how emoji does it for `global.env`:

https://github.com/NodeBB/nodebb-plugin-emoji/blob/44d01f5fae28af6e442be167ddb9b99b1f92b4de/lib/types.d.ts#L169

And here's how calendar does it for `request.uid`:

https://github.com/pitaj/nodebb-plugin-calendar/blob/main/src/lib/express.d.ts

**Pull request closed without merging**
