### PR TITLE
Clarify that this is the default digest setting

### PR DESCRIPTION
**Pull request by phit**
When digests are enabled this is already the case, not sure why a different wording was chosen for digest off.

### CODE REVIEW

**Comment by pauljherring** [comment]
> For me the currently implies the current user settings are set to not receive any or digests are disabled globally regardless of user setting.

Simple: 

> Currently, this community does not send <del>out</del><ins>you</ins> email digests

**Comment by phit** [comment]
@pauljherring well that would be simply wrong, as that text is based on the global default..

**Comment by pauljherring** [comment]
Ah - I got the (apparently wrong) impression that this was a user setting.

**Comment by julianlam** [comment]
I think this all points to the fact that the line itself could be better explained. FWIW it displays what the board default (admin set value) is set to. You can override the board default in the UCP.

**Comment by julianlam** [comment]
Hopefully the above commit :point_up: reduces the confusion.

**Comment by phit** [comment]
yep, sounds a lot clearer! thanks

**Pull request closed without merging**
