### PR TITLE
fix:removing category images via ACP

### PR DESCRIPTION
**Pull request by MegaGM**
and again it's about https://community.nodebb.org/topic/4054/introducing-the-nodebb-0-7-0-persona-preview/63

### CODE REVIEW

**Comment by julianlam** [comment]
:anguished: Did I remove this code accidentally?

**Comment by MegaGM** [comment]
Apparently you did :anguished:

**Comment by julianlam** [comment]
We haven't imported the old signatured over yet, please sign again please: https://docs.google.com/forms/d/1KrniXs3pwK8dMeAZnnQz2D07ne7LjJTYIYwJrpDqgnE/viewform?usp=send_form

**Comment by MegaGM** [comment]
I've found chunk that you've deleted
https://github.com/NodeBB/NodeBB/blob/7cdfe143ab965153437141357764e8c0c0ead1db/public/src/admin/manage/category.js#L158-L170

**Comment by julianlam** [comment]
Cheers :beers:

**Pull request merged**
