### PR TITLE
Remove jshint because its not used

### PR DESCRIPTION
**Pull request by HeeL**
jshint has not been used in Project. There is no package or task to lint with jshint. The rules weren't being followed, at the moment there are more than 67k errors.
This will be removed in favour of eslint that has been already introduced in project and will be slowly filled with meaningful rules.

### CODE REVIEW

**Comment by julianlam** [comment]
We use jshint... in our IDEs 😄

**Comment by HeeL** [comment]
I've assumed that but why when I run jshint on root directory there are 67k errors?

**Comment by julianlam** [comment]
Is it reading node_modules too?

**Comment by HeeL** [comment]
I would expect jshint to have some ignore list or use the one from git.  Anyway, if you say you are using it, there is no reason not to trust you ;)

**Pull request closed without merging**
