### PR TITLE
noscript support

### PR DESCRIPTION
**Pull request by An-dz**
These changes will allow login, logout and posting as long as the theme has support for it.

So this must go along with the pull requests in:
- [nodebb-theme-persona](https://github.com/NodeBB/nodebb-theme-persona/pull/355)
- [nodebb-plugin-composer-default](https://github.com/NodeBB/nodebb-plugin-composer-default/pull/86)

Theme creators that wish to add support for noscript need to add similar changes as those in above pull requests. They are listed to ease the process:

- Make sure _login_, _logout_, _register_ & _posting areas_ are **forms** with POST method and with a submit button;
- Add `<input type="hidden" name="_csrf" value="{config.csrf_token}" />` to all above forms;
- Add `<input type="hidden" name="noscript" id="noscript" value="true" />` to the login, logout & register forms;
- Add `name="content"` to the _textarea_ of composer;
- Use `a` tag with _href_ attribute `{config.relative_path}/compose?tid={tid}&title={title}` to _Reply_ buttons;
- Use `a` tag with _href_ attribute `{config.relative_path}/compose?cid={cid}` to _New Topic_ buttons;
- Post composer form must have the same changes as in [nodebb-plugin-composer-default](https://github.com/An-dz/nodebb-plugin-composer-default/commit/9c05a471c0f61990e33946dde3086a5cf9919c8a#diff-d37eebe6d30168916fb87de1281e67d0)

**Extra tip:**\
Use the HTML + CSS trick for creating dropdown menus:
```html
<label for="check">Click me</label>
<input type="checkbox" id="check">
<ul>...</ul>
```
```css
#check, ul {
   display: none;
}
#check:checked + ul {
   display: block;
}
```

### CODE REVIEW

**Comment by pitaj** [comment]
Are these changes backwards compatible?

**Comment by An-dz** [comment]
I highly believe so, at least I tried to make sure themes that don't use these won't break, but I did not extensively tested them, just a few the default ones.

I'll continue testing with them and download at least one new to fully test, but I guess it would be better if more people could test it.

**Comment by An-dz** [comment]
I just installed two themes, nodebb-theme-slick - newest theme, last commit 3 days ago - and nodebb-theme-material-dark - oldest theme, last commit March 2016.

My quick tests showed no problems, could login, logout and post without problems.

**Comment by psychobunny** [comment]
I haven't checked this out yet, but how does this deal with errors after form submission? Ex. too many/not enough characters in title/content; username taken on registration, etc.

**Comment by An-dz** [comment]
It just returns a page with a text as [[error:_erroReason_]] as I could not find how to build the body.

**Comment by pitaj** [comment]
Maybe it would be best to return a 400 page with the given error.

**Comment by An-dz** [comment]
I thought about simply doing as the version with script, that is to show the error box with the localised text. As that's why this part exists in the template:
```html
<div class="alert alert-danger" id="login-error-notify" <!-- IF error -->style="display:block"<!-- ELSE -->style="display: none;"<!-- ENDIF error -->>
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<strong>[[login:failed_login_attempt]]</strong>
	<p>{error}</p>
</div>
```

**Comment by An-dz** [comment]
I've been able to show the error messages in the page itself but what I did is too dirty. If an error on the page rendering happens it can't be resolved as it does not have the correct `next` function.

The asynchronous nature of the code also does not really help to find how I could make a "correct" request or to somehow attach the correct `next` function.

**Comment by psychobunny** [comment]
IMO @pitaj is on the right track: as this is noscript, we don't need to be too fancy here... a 400 page with the error message and a link to go back is more than enough, if you can figure that out ;)

**Comment by An-dz** [comment]
I'm almost done, but there's one thing though, I can't make a link to go back because JS is disabled. I'll just add a text explaining to go back instead.

**Comment by An-dz** [comment]
I think I'm done. I added support for registering without scripts and created tests for registering, logging in and logging out without scripts.

**Comment by pitaj** [comment]
Hi @An-dz. Really appreciate the work you've done here. 

However, I think the issue with this PR is that you're doing too much at once. Please submit these things separately:
- noscript login
- noscript logout
- noscript compose

I realize this is asking a lot, but it really does make it easier for us to consider, and the smaller PRs therefore will be merged more quickly.

Thanks

**Comment by An-dz** [comment]
Thanks for the info @pitaj, I'll create branches then. I'll also update the code.

**Pull request closed without merging**
