### PR TITLE
Fixing 'Go to last read' popup text

### PR DESCRIPTION
**Pull request by RaceProUK**
Since clicking the popup goes to the last _read_ post, not the last unread

I've only changed English and untranslated resources (I only speak English :blush:)

### CODE REVIEW

**Comment by pichalite** [comment]
I think changes to language strings should go to the transifex site https://www.transifex.com/nodebb/nodebb/

**Comment by RaceProUK** [comment]
Ah, I did not know that :blush:

/me wanders over there to check things out

**Comment by pichalite** [comment]
create an account, join the nodebb team and you will see all the languages listed. change the translation there and the NodeBB devs will pull the updated strings.

**Comment by RaceProUK** [comment]
Does that apply to en-GB too? Because all I got were errors trying to view that file.

**Comment by pichalite** [comment]
en-GB may be locked in transifex. you should be able to translate others.

**Comment by RaceProUK** [comment]
OK, I think I've figured it out now. But that doesn't really help with the source phrase, which also needs correcting.

**Comment by pichalite** [comment]
you can probably leave the en_GB change in this PR and remove everything else.

**Comment by RaceProUK** [comment]
That looks to be right :smile:

**Pull request merged**
