### PR TITLE
Docker: Insure we're on a recent & Long Time Support (LTS) version of node.

### PR DESCRIPTION
**Pull request by edasque**
Also added some helpful comment to explain what is doing what and the choices made.

### CODE REVIEW

**Comment by edasque** [comment]
As an aide, Travis CI currently tests on [nodejs 0.10, 0.11, 4.0 & 4.1. 4.1] (https://github.com/NodeBB/NodeBB/blob/master/.travis.yml), a current LTS release seems to be the best choice for performance & stability in a Docker container. 5.0 won't be around of long and isn't an environment NodeBB is currently tested on.

**Comment by edasque** [comment]
Can we get this merged?

**Comment by edasque** [comment]
@julianlam, now that #3816 is closed, can we push this through?

**Comment by julianlam** [comment]
Waiting on @Alpacatty's thoughts on this :smile:, but looks good to me!

**Comment by julianlam** [comment]
The "docker-builds" repository has been deleted. @xaoseric, please update the Dockerfile here if necessary :smile:

**Pull request merged**
