### PR TITLE
Removed invalid options for the sendmail transport

### LINKED ISSUE #8575: Sendmail is Basically an Impossibility Right Now
- **NodeBB version:** 1.14.3
- **NodeBB git hash:** 28970b030d21a9e839804b0c40e0ed1c520502ac
- **Installed NodeBB Plugins:** 
 * nodebb-plugin-composer-default (installed, enabled)
 * nodebb-plugin-dbsearch (installed, enabled)
 * nodebb-plugin-emoji (installed, enabled)
 * nodebb-plugin-emoji-android (installed, enabled)
 * nodebb-plugin-jwt-oauth2 (installed, disabled)
 * nodebb-plugin-markdown (installed, enabled)
 * nodebb-plugin-mentions (installed, enabled)
 * nodebb-plugin-s3-uploads-updated (installed, disabled)
 * nodebb-plugin-soundpack-default (installed, enabled)
 * nodebb-plugin-spam-be-gone (installed, disabled)
 * nodebb-rewards-essentials (installed, enabled)
 * nodebb-theme-lavender (installed, disabled)
 * nodebb-theme-persona (installed, enabled)
 * nodebb-theme-slick (installed, disabled)
 * nodebb-theme-vanilla (installed, disabled)
 * nodebb-widget-essentials (installed, enabled)
- **Database type:** redis
- **Database version:** `Redis server v=3.2.12 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=7897e7d0e13773f`
- **Exact steps to cause this issue:**
 1. Tried to send a test email through the admin interface with "Custom Service" selected (no SMTP connection/host, etc... provided)
- **What you expected:**
I expected an email to be sent via `sendmail` on my `localhost`
- **What happened instead:**
I received no email. I tailed the logs and tried again. I saw the following error message:
```
error: Error: connect ECONNREFUSED 127.0.0.1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

Why would it be trying to connect to an SMTP server when I didn't provide any info to connect to one?

I've spent about an hour tracing and debugging the logic and why **Nodemailer** wasn't defaulting back to the `sendmail` transport. As it turns out, NodeBB's code is properly falling back to the sendmail transport but the sendmail transport isn't actually a sendmail transport at all... it's an SMTP transport. I took me a while to figure out why, though because all the code looks correct. So I did some testing outside NodeBB with Nodemailer and discovered the following issue:

This code works perfectly fine:

```javascript
// workingTest.js
const emailer = require('nodemailer');
const transporter = emailer.createTransport({
    sendmail: true,
    host: 'localhost',
    newline: 'unix',
    pool: false,
    rateLimit: 2,
    rateDelta: 1000,
});

const email_opts = {
    from: '"Forum Administrator" <webmaster@example.org>',
    to: 'foobar@example.org',
    subject: 'Testing Forum Sendmail',
    text: 'Testing for some stuff...',
    html: 'testing and more testing...',
};

transporter.sendMail(email_opts, (err, res) => {
    if (err) console.error(`Email Send Failed! Error: ${err}`);
    else console.log('It worked!');

    process.exit(0);
});
```

But the following code does not...

```javascript
// failingTest.js
const emailer = require('nodemailer');
const transporter = emailer.createTransport({
    sendmail: true,
    pool: true, // <------- This is the issue
    host: 'localhost',
    newline: 'unix',
    pool: false,
    rateLimit: 2,
    rateDelta: 1000,
});

const email_opts = {
    from: '"Forum Administrator" <webmaster@example.org>',
    to: 'foobar@example.org',
    subject: 'Testing Forum Sendmail',
    text: 'Testing for some stuff...',
    html: 'testing and more testing...',
};

transporter.sendMail(email_opts, (err, res) => {
    if (err) console.error(`Email Send Failed! Error: ${err}`);
    else console.log('It worked!');

    process.exit(0);
});
```

As it turns out, if you provide `pool: true` as an option to the `nodemailer.createTransport()` method, **sendmail** is *effectively eliminated* as an option.

From the Nodemailer source code (https://github.com/nodemailer/nodemailer/blob/e3055c49f5247d002f084c28f3cbe39aa34117eb/lib/nodemailer.js#L43) (did a git blame, it's been this way for 4 years... so it's nothing new):

```javascript
if (options.pool) { // <--- this...
    transporter = new SMTPPool(options);
} else if (options.sendmail) { // <-- eliminates the possibility of this in NodeBB
    transporter = new SendmailTransport(options);
} else if (options.streamTransport) {
    transporter = new StreamTransport(options);
} else if (options.jsonTransport) {
    transporter = new JSONTransport(options);
} else if (options.SES) {
    transporter = new SESTransport(options);
} else {
    transporter = new SMTPTransport(options);
}
```

Unfortunately, the **NodeBB** source code has `pool: true` hardcoded for the sendmail transport:
https://github.com/NodeBB/NodeBB/blob/9fd377532553b14e98c64e15b1c441f126afa416/src/emailer.js#L28

```javascript
Emailer.transports = {
	sendmail: nodemailer.createTransport({
		sendmail: true,
		newline: 'unix',
		pool: true,
		rateLimit: meta.config['email:sendmail:rateLimit'],
		rateDelta: meta.config['email:sendmail:rateDelta'],
	}),
	smtp: undefined,
};
```

I recommend we remove this line or at least make it configurable with the config file or with a setting in the admin section. I'd like to hear your thoughts on solving this issue. I'd be more than happy to put in a PR with the recommended solution.

Thanks!

### PR DESCRIPTION
**Pull request by kylefarris**
Removed invalid options for the sendmail transport that were causing Nodemailer to return the SMTPTransport instead.

Fixes #8575

### CODE REVIEW

**Comment by pitaj** [comment]
I think these should be moved to apply to the SMTP transport instead, not removed entirely.

Also, just removing them from the code doesn't remove the options from the admin menu.

**Comment by kylefarris** [comment]
Before we add those options to the SMTP transport, we should consider that Nodemailer has deprecated the options and will be removing them in future updates: https://nodemailer.com/smtp/pooled/#deprecated-options

I can still make the swap if you'd like, but, we could also just remove the options from the interface entirely. At the very least,  a note should be made in the code about the deprecation.

**Comment by pitaj** [comment]
Ah, in that case, remove rateLimit and rateDelta entirely, and add pool to the SMTP options. Maybe even make it an nconf option.

Regardless, you'll need to make changes to the admin templates and translations to remove the sendmail options.

**Comment by kylefarris** [comment]
No problem. I removed the deprecated options from the admin interface and added a new one for toggling pooled connections for the SMTP Transport. Tested on my dev machine and it all looks good there. Tests passed on there as well.

**Comment by barisusakli** [comment]
LGTM

**Pull request merged**
