### PR TITLE
Display compatible and current NodeBB version when plugin is not compatible

### PR DESCRIPTION
**Pull request by FokkeZB**

### CODE REVIEW

**Comment by julianlam** [comment]
I made some changes to this code in `master`, so it would conflict if I pulled changed in from there. Please take a look at the new behaviour and make a PR against that branch.

Thanks!

**Comment by FokkeZB** [comment]
not sure where to do it:
https://github.com/NodeBB/NodeBB/blob/master/src/plugins/load.js#L58

**Comment by julianlam** [comment]
This commit may help: https://github.com/NodeBB/NodeBB/commit/e382dcab135d587b15fbd7ec652e24de09d42bfd#diff-e3868d05bc2e2038bd4f86b59cb8f95c

**Comment by julianlam** [comment]
Keep in mind that instead of showing the warnings repeatedly for every plugin, I now collect the potentially incompatible plugins and show a list.

It is up to you to determine whether or not showing the version numbers is necessary.

**Pull request closed without merging**
