### PR TITLE
Admin option to allow users to flag their own posts

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by BenLubar** [comment]
https://github.com/NodeBB/nodebb-theme-persona/pull/333
https://github.com/NodeBB/nodebb-theme-vanilla/pull/89

**Comment by pichalite** [comment]
@BenLubar In what scenario would a user need to flag their own posts?

**Comment by pauljherring** [comment]
One we've had recently is when a user's intended single comment resulted in a sub-thread that the user wanted forking into a separate thread.

**Comment by BenLubar** [comment]
The most common reason would probably be "oops, I posted this in the wrong category".

**Comment by pichalite** [comment]
I think the flagging system needs more changes for what you are trying to accomplish. The scenarios you described are kind of requests to Admins/Mods. These should not be counted as flags against a user.

**Comment by pitaj** [comment]
Open an issue detailing use cases and solution proposals, please.

**Pull request closed without merging**
