### PR TITLE
fixes #4992

### LINKED ISSUE #4992: admin/general/navigation doesn't work
```
navigation.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:25 Uncaught TypeError: $(...).sortable is not a functionnavigation.init @ navigation.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:25(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:23873execCb @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21370check @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21359(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21363(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21348(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21364y @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21347emit @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21364check @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21360(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21363(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21348(anonymous function) @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21364y @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21347emit @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21364check @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21360enable @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21364init @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21357I @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21354completeLoad @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21369onScriptLoad @ acp.min.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:21370
navigation.js?v=f97c6c16-d8dd-4f2e-a9ac-c2b2cd3fde9a:17 Uncaught TypeError: $(...).html(...).find(...).draggable is not a function
```

### PR DESCRIPTION
**Pull request by pichalite**

### CODE REVIEW

**Comment by barisusakli** [comment]
Are we going to call this on every page that needs jqueryui, isn't it better to include jqueryui on acp on page load.

**Comment by pichalite** [comment]
well... it's only required on navigation, users and flags pages right?

**Comment by julianlam** [comment]
err... well it's an rjs module. Can it be required in core similar to how plugins define rjs modules?

Then we can just `require(['jqueryUI']);` or whatever the name is.

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/meta/js.js#L76

Add it here.

**Comment by julianlam** [comment]
Whoops my bad, actually, add it to the section below it, `modules`.

**Comment by pichalite** [comment]
@julianlam Ok, added it to modules and removed call for app.loadJqueryUI from admin screens.

**Comment by pichalite** [comment]
@julianlam

**Comment by julianlam** [comment]
hello.l

**Pull request merged**
