### PR TITLE
feat: column based view on wide priv. tables

### PR DESCRIPTION
**Pull request by gasoved**
preview

### CODE REVIEW

**Review by julianlam — COMMENTED** [review]
This looks solid. My only concern is actually the opposite of what which @psychobunny mentioned...

I am afraid that the expectation for clicking "Copy privileges to children" would actually be to copy **all** of the privileges, when now it only copies the subset shown in the filtered privileges.

Worse yet, I think it's a situation where there's no clear consensus on what that button should do given this UX. ~50% will say it should copy all, ~50% will say it should copy the subset. +/- 50% polling error because I made this statistic up.

Options here are:

1. Update the button label so that it is clear that it only copies the **subset**
2. Introduce another button that copies to/from **all** privileges to children/all

**Comment by julianlam** [comment]
image

Instead of a three-button "copy to all" "copy to children" and "copy from category", we would need to rework this to show two "copy" menus: "copy these privileges" "copy all privileges"

When clicked, it would open a dropdown that allows you to copy to/from all/children

**Comment by psychobunny** [comment]
> I am afraid that the expectation for clicking "Copy privileges to children" would actually be to copy all of the privileges, when now it only copies the subset shown in the filtered privileges.

I see the opposite but to your point, it's not clear. Bootbox confirm modal telling what's actually going to happen and call it a day imo

**Comment by psychobunny** [comment]
Stretch goal (sorry don't have my ipad on me lol):

confirm-privs

**Comment by julianlam** [comment]
Bootbox modal is perfectly acceptable. @gasoved if you could implement :smile:

**Comment by gasoved** [comment]
How does it look like now?

**Pull request merged**
