### PR TITLE
Add API endpoint analogs to websocket interface

### PR DESCRIPTION
**Pull request by AccaliaDeElementia**
includes `post.getPost`, `topic.getTopic`, `category.getCategory`, `user.getUserBy*`

These additional websocket interfaces, along with the existing functionality should enable integrations to use the websocket interface exclusively after authentication

Category, Post, and Topic endpoints enforce user read permissions so there should not be a risk of data leak there.

I'm less sure of the `user.getUserBy*` methods but as these were cribbed from the REST API endpoints and behave identically in my testing any data leak possibility already exists in the REST API endpoint

### CODE REVIEW

**Comment by barisusakli** [comment]
This looks good, but there is quite a bit of duplication. Check the file `controllers/api.js` it has many of this same functionality so with some refactoring both can share the same code.

**Comment by AccaliaDeElementia** [comment]
That's a good point about the duplication, and something i would like to see deduplicated.

My initial plan was to get the basic functionality into core so that my project could be unblocked and then issue supplementary PRs that would refactor both endpoints to use common code where applicable.

I can perform the deduplication refactor now and reissue the PR if that's preferred, I was merely hesitant to change code outside of the new functionality i needed without having a better understanding of the entire project.

**Comment by barisusakli** [comment]
It's cool, I can probably merge this PR later today/tomorrow and do the necessary refactors.

**Comment by AccaliaDeElementia** [comment]
cool then. Thanks!~

**Comment by julianlam** [comment]
I was _wondering_ why my local `v1.x.x` and `origin/master` differed. This PR was made to the wrong branch.

**Comment by julianlam** [comment]
Can't cherry-pick either of those commits since it looks like the methods added by @AccaliaDeElementia were re-added by @barisusakli in 8d9f7d8e19161a7b62a479f772cd4828059d7cb9.

What a mess...

**Comment by julianlam** [comment]
Okay, so [we just have duplicated code...](https://github.com/NodeBB/NodeBB/blob/v1.x.x/src/socket.io/user.js#L340-L392). Looks like a re-release of v1.0.1 is in order.

**Comment by BenLubar** [comment]
On top of that, [the build of v1.0.1's docker image](https://hub.docker.com/r/benlubar/nodebb/builds/bujmfvdk9njvjiyjyqpxvg6/) failed because Docker forgot what NodeJS was.

**Comment by julianlam** [comment]
@BenLubar Yikes, hope that's not related to anything we did!

**Comment by BenLubar** [comment]
@julianlam nope, not your fault. The timeout happened before it even looked at your code. I told it to [try again](https://hub.docker.com/r/benlubar/nodebb/builds/bmhswnrihf4mwoaemjzmpnv/).

**Comment by AccaliaDeElementia** [comment]
:'(

i'm sorry! i promise to commit to the correct branch next time!

**Comment by julianlam** [comment]
It's ok @AccaliaDeElementia, no harm no foul. Just grumpy because it's end of workday for me :wink:

**Comment by AccaliaDeElementia** [comment]
well i'd be grumpy too!

:-)

it's cool though.

i expect we'll be seeing much more of each other on here as i ramp up my development of [SockBot](https://github.com/SockDrawer/SockBot) NodeBB edition

**Comment by julianlam** [comment]
Cool! 

Are you using the write api with an api key granted by @ben_lubar? You should use the write api... it's pretty neat :smile:

**Comment by AccaliaDeElementia** [comment]
no.

it's a generic bot so it logs in as a user and uses the standard user API.

;-)

**Comment by psychobunny** [comment]
Here I was wondering if tdwtf coming on board would result in over 9000 issues on our tracker. Instead you guys are making cool PRs :) thanks!

**Comment by AccaliaDeElementia** [comment]
Don't worry, the issues are coming, but then so will the PRs to fix them!

**Pull request merged**
