### PR TITLE
#2893 increment --debug-brk port value when forking js-minifier child pr...

### PR DESCRIPTION
**Pull request by EvSpirit**
Solution of #2893 ticket (fork of js minifier was incorrect when debugging with --debug-brk option)

### CODE REVIEW

**Comment by EvSpirit** [comment]
Nop, it's not quite correct - if you don't connect to child process, it will hang up. Give me a few minutes to fix it :)

**Comment by EvSpirit** [comment]
Now it's ok. I commented out one line with --debug-brk and --nolazy option setup with incremented debugPort value. I don't think it's necessary to debug minifier.js process, but still, if someone needs that, one will have to uncomment one line with proper params and comment out other.

**Comment by barisusakli** [comment]
@EvSpirit have you signed https://docs.google.com/forms/d/1KrniXs3pwK8dMeAZnnQz2D07ne7LjJTYIYwJrpDqgnE/viewform

**Comment by EvSpirit** [comment]
@barisusakli , I've just signed it, should be ok now

**Pull request merged**
