### PR TITLE
Added Ukrainian language to Transifex config

### PR DESCRIPTION
**Pull request by mortiy**
Ukraininan language is not present in Transifex config, consequently not being pulled by @nodebb-misty.

### CODE REVIEW

**Comment by julianlam** [comment]
Ah, I did not realise, thank you! :smile:

**Comment by mortiy** [comment]
Hey @julianlam,
Do you know when this pull request will be merged?

**Comment by mortiy** [comment]
@MegaGM, what's wrong with my question?

**Comment by julianlam** [comment]
Sorry for the delay, good to go! :smile:

Please ensure language.json uses the same code as the language (uk)

**Comment by julianlam** [comment]
Misty will pull Ukrainian translations in tomorrow morning

**Pull request merged**
