### PR TITLE
newer node = faster node

### PR DESCRIPTION
**Pull request by faddat**
just made it so that @Alpacatty's docker container would use the latest nodejs.

### CODE REVIEW

**Comment by edasque** [comment]
I personally don't love that change. Dockerfiles are supposed to point to a specific version of software (or at least a stable family) of software. Pointing to latest is an anti-pattern since you're potentially introducing new versions of the underlying platforms that haven't been tested with even the master of your application.

I believe that something like:
```
FROM node:4-wheezy
```
would be more appropriate. It allows to get the latest of a stable branch of OS, the latest of a Stable release. As it is ```node`` would just point to the latest of node, which is 5.x and probably mostly untested at this point.

**Comment by Alpacatty** [comment]
@edasque is right. Although you'd want to use the `-onbuild` version rather than the `-wheezy` one, as that makes sure every dependency from `package.json` is installed.

**Comment by edasque** [comment]
I see what you mean, @Alpacatty. Not sure I like that it's based on Jessie but your mileage may vary. Interesting approach to the dependency game by doing a npm install as part of the node image on ONBUILD. I wonder if it'd ideally require a ```upgrade``` between the setup & the app run, in case it's require. I can see it failing if you're pulling a NodeBB that's requires a, say, redis update.

**Comment by Alpacatty** [comment]
To be fair @edasque, I've never performed an upgrade with this image. I'm not currently running NodeBB in production anymore, so if you (or anyone else) wants to take this over and work on that, please feel free to ^_^

Though - and I'm not versed enough in Debian to know all the details, but - isn't Jessie considered stable now?

**Comment by edasque** [comment]
I need to put some more thoughts into it but I'll be happy to send a pull request at some point. @Alpacatty, Jessie is fine, I am just more used to using Wheezy (Ubuntu) though for no particular technical reason, I must confess.

**Comment by edasque** [comment]
I suggested this approach instead: https://github.com/NodeBB/NodeBB/pull/3822

**Comment by julianlam** [comment]
Am willing to merge either depending on concensus :smile:

**Comment by edasque** [comment]
Since @faddat doesn't seem responsive, I will reaffirm that #3822 is a better approach. As mentioned there and furthermore NodeBB Travis CI currently tests on nodejs 0.10, 0.11, 4.0 & 4.1. 4.1, a current LTS release seems to be the best choice for performance & stability in a Docker container. node.js 5.0 won't be around for long as it's a temporary stable before 6.0 comes out (an LTS release) and isn't an environment NodeBB is currently tested on, node a.k.a. latest wouldn't be a good choice in those circumstances.

**Comment by faddat** [comment]
To be honest with you my knowledge of node is not extensive enough to have a well-formed opinion on the matter.  Since you support your argument with facts and links, and there's no one objecting I'm going to say, OK, because node 4 is certainly (in my experience) faster than what's currently used in the Dockerfile.  

I do get what you mean about version-pegging an image, thus rendering it more of a known quantity.  Personally, I'd go for the "automatic" updates of just using the node:latest, but a lot of it boils down to taste and I see nothing wrong with "latest  stable".  Trouble is, opens up the technical debt of Dockerfile maintenance.  Either way, (4 or latest) the image will be improved through a revamp.

**Comment by Alpacatty** [comment]
@julianlam what Node version does the NodeBB team currently recommend their software to be run on? Pin it to that one :stuck_out_tongue_winking_eye: 

@faddat pinning does mean occasional Dockerfile maintenance, but as Node now follows semver not pinning it to a major version means your automatic updates will be pulling in breaking changes.

**Comment by edasque** [comment]
@Alpacatty , let's remember this doesn't pin to a specific version but a specific major version. Since the most up to date node that nodebb tests against is 4.2.x and it's the most up to date Long Term Support version (as opposed to the 5.x branch which is ephemeral in nature).

The automatic updates of latest stable can get you in trouble for sure and node:latest is inherently dangerous. An update in latest can introduce breaking change. node-4-onbuild will not.

**Comment by julianlam** [comment]
@Alpacatty We develop on 0.12, but as v4 is LTS, I will vouch for that one. I develop on v4 as well, and 0.9.0 is confirmed to work fine on v4.

v0.8.x does not, and only works on `<=` v0.12

**Comment by faddat** [comment]
given what @julianlam is saying, I'm now moving to support 0.4 and an eye
on the Dockerfile.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by edasque** [comment]
Van we close this and merge #3822 ?

**Comment by faddat** [comment]
Seconded.  I'd do node 4.1 but that's just me...

**Comment by edasque** [comment]
4.1 instead of 4.x which brings 4.2.1 currently? Why @faddat ?

**Comment by faddat** [comment]
*eep*

4.x then.... Highest of the LTRs.....

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by edasque** [comment]
Yes, can we close this PR and push for #3822 ?

**Comment by faddat** [comment]
Yes!  I'll close this PR now!  #3822 it is!

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Pull request closed without merging**
