### PR TITLE
Use NPM package ip to display ip

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@julianlam

This PR is cleaner, hope this goes like this...

**Comment by Justman10000** [comment]
@julianlam

**Comment by julianlam** [comment]
@Justman10000 There is still no need to introduce a new dependency just for reporting the external IP.

The web installer listens on `0.0.0.0`, not on a specific IP address. Any IP that resolves to that machine will work. Therefore reporting the external IP is not always correct.

**Comment by Justman10000** [comment]
> @Justman10000 There is still no need to introduce a new dependency just for reporting the external IP.
> 
> The web installer listens on `0.0.0.0`, not on a specific IP address. Any IP that resolves to that machine will work. Therefore reporting the external IP is not always correct.

Not really! It's just an info text!

**Comment by julianlam** [comment]
That's right, which is why it needs to be *correct*.

**Comment by Justman10000** [comment]
@julianlam

Better?

**Comment by Justman10000** [comment]
@julianlam

**Comment by Justman10000** [comment]
@julianlam

**Comment by julianlam** [comment]
No, @Justman10000, I will not allow the introduction of an entire dependency just for a single line output to console.

**Comment by Justman10000** [comment]
> No, @Justman10000, I will not allow the introduction of an entire dependency just for a single line output to console.

Well, in that case, like so many others, you wasted my time again, and lost another user! No more PRs or any other support from me!

**Comment by julianlam** [comment]
That's great, have a good day.

**Comment by Justman10000** [comment]
> That's great, have a good day.

Thanks, but I don't know what's so great about wasting someone's time... I guess you don't care if you hurt someone's feelings and who leaves your community... Well, not my bad luck!

**Comment by Justman10000** [comment]
> That's great

I don't know what's so great about wasting someone's time... I guess you don't care if you hurt someone's feelings and who leaves your community... Well, not my bad luck!

**Pull request closed without merging**
