### PR TITLE
Minor styling updates to ACP Categories page

### PR DESCRIPTION
**Pull request by pichalite**
Changes this...
capture

to this...
image

### CODE REVIEW

**Comment by psychobunny** [comment]
You're on a roll lately with the PRs :)

**Comment by pichalite** [comment]
You would have got more PRs if I was NOT still trying to get a hang of how things are done properly in node js world. :smile:

**Comment by barisusakli** [comment]
Without the children-placeholder it's not possible to drag a category and make it a child of another one.

**Comment by pichalite** [comment]
Oops... I didn't know you could do that :disappointed:

**Comment by barisusakli** [comment]
Yeah maybe there is a way to make it work without those ugly dashed borders

**Comment by pichalite** [comment]
I agree those dashed borders are ugly. It was not clear that you could drag a category to make it a child of another one anyway. May be we could add the children-placeholder back without the dashed borders?

**Comment by barisusakli** [comment]
Not sure if I remember correctly but I think I couldn't get it to work without the border :laughing: feel free to try, I will merge if it does.

**Comment by pichalite** [comment]
It worked for me without the borders. Submitted a PR.

**Pull request merged**
