### PR TITLE
Added filter:posts.build and postData.tools array for adding buttons

### PR DESCRIPTION
**Pull request by dwendt**
Adds a filter that allows modification of post data sent to the templating engine.

Requires PR https://github.com/NodeBB/nodebb-theme-persona/pull/158

### CODE REVIEW

**Comment by barisusakli** [comment]
You can probably use [`filter:post.getPosts`](https://github.com/NodeBB/NodeBB/blob/master/src/posts.js#L64) for this.

It receives an array of posts.

**Comment by dwendt** [comment]
It doesn't seem that there's any way to get the data from that filter into the templating engine though.

**Comment by barisusakli** [comment]
That hook is called whenever posts are loaded so when you load a topic it gets called.

You can add your tools array into each post in that hook. Which will become available in the templates.

**Comment by dwendt** [comment]
...yep! just confirmed that totally works on persona with this merge NodeBB/nodebb-theme-persona#158

**Pull request closed without merging**
