### PR TITLE
Use Github Action as a release pipeline to Docker

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
This action workflow will execute whenever master is pushed, a tag is pushed, or be ran manually. It also supports multi-architecture build thanks to buildx and qemu

### CODE REVIEW

**Comment by julianlam** [comment]
Don't we already automatically push to docker hub 🤔

Or might be docker monitors this repo for new releases

**Comment by stevefan1999-personal** [comment]
@julianlam hmm, but far as I know it only builds for amd64, which is not suitable for RPi 4/Graviton2 use

**Review by pitaj — COMMENTED** [review]
Given this is for docker, can you rename the file to docker.yml and change the name to "Docker build" instead?

**Comment by julianlam** [comment]
@oplik0 Okay. Let me give that a try.

**Comment by julianlam** [comment]
@stevefan1999-personal Can you advise on this error?

```
 #17 [linux/arm/v7 5/6] RUN npm install --only=prod &&     npm cache clean --force
#17 301.0 
#17 301.0 > sharp@0.29.1 install /usr/src/app/node_modules/sharp
#17 301.0 > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#17 301.0 
#17 304.0 sharp: Installation error: Use with glibc 2.24 requires manual installation of libvips >= 8.11.3
#17 304.1 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
```

**Comment by julianlam** [comment]
One other thing is, we need the image pushed to `nodebb/docker`, it looks like it currently pushes to `<username>/nodebb`, is that right?

**Pull request merged**
