### PR TITLE
provide more data in the hook

### PR DESCRIPTION
**Pull request by xidui**
Currently the data provided in the filter:category.topics.get does not enough. I think the payload should also be included.

### CODE REVIEW

**Comment by julianlam** [comment]
Looks like there was a bad merge or something. Too many commits that don't belong to you. Please resubmit, though what is it in the data variable you need?

**Comment by xidui** [comment]
@julianlam 
I want the category id in the `filter:category.topics.get` hook.

**Comment by xidui** [comment]
@julianlam 
I think the payload should included in the hooks which will give much more flexibility for others to develop plugins.
I found that not only this, but other hooks also lacks this payload.
You designed to be so?

**Comment by julianlam** [comment]
Best to pass in the cid explicitly, or retrieve from the topics themselves.

**Comment by xidui** [comment]
```
Categories.getCategoryTopics = function(data, callback) {
		async.waterfall([
			function (next) {
				plugins.fireHook('filter:category.topics.prepare', data, next);
			},
			function (data, next) {
				Categories.getTopicIds(data.set, data.reverse, data.start, data.stop, next);
			},
			function (tids, next) {
				topics.getTopicsByTids(tids, data.uid, next);
			},
			function (topics, next) {
				if (!Array.isArray(topics) || !topics.length) {
					return next(null, {topics: [], uid: data.uid});
				}

				for (var i=0; i<topics.length; ++i) {
					topics[i].index = data.start + i;
				}

				plugins.fireHook('filter:category.topics.get', {topics: topics, uid: data.uid}, next);
			},
			function (results, next) {
				next(null, {topics: results.topics, nextStart: data.stop + 1});
			}
		], callback);
	};
```
This function not always give the topics with the same category. It depends on the `set`, which may be modified by other plugins.

**Comment by xidui** [comment]
Why not just pass the payload?
Once a user need a new variable in the hook, he should modify the source code, then self-maintain  his own fork forever since the code is not consistent with this repo. Seems not a good practice. How do you feel?

**Comment by julianlam** [comment]
Yes, I am also not in favour of people maintaining their own fork. If there is a desire for a particular set of data to be passed in the hook, then we will add it.

I don't have any objection to passing the cid in, although I am not sure passing the entire `data` payload is the way to go. I'd prefer just `{ cid: data.cid }`.

**Comment by barisusakli** [comment]
>This function not always give the topics with the same category
This is why we dont pass the cid in because the topics might be coming from different cids.

**Pull request closed without merging**
