### PR TITLE
Fixing some issues with acp category page

### PR DESCRIPTION
**Pull request by yariplus**
I made a naming change and fixed a few things that seem to have gotten messed up at some point.

The background image size was called imageClass and "Image Class". That's confusing to me because it's not a class, nor should the end-user know what "Image Class" is supposed to mean. Changed to bgSize and "Background Image Size".

Colorpicker had an invalid on change selector.

Colorpicker on change was hijacking the background image.

Image upload was hijacking the background size.

Template was not checking the background size.

Background size now changes on change.

### CODE REVIEW

**Comment by barisusakli** [comment]
Not sure how important but changing the property name will cause old values to not work, ie if you set `imageClass` to something after this change you will have to reset them again.

**Comment by julianlam** [comment]
Might benefit from an upgrade script then...

**Comment by yariplus** [comment]
Up to you guys. I would be okay with leaving imageClass as is if it might cause problems.

Another thing is, most themes I've seen would benefit from calling helpers.generateCategoryBackground instead of calling the styles directly anyway.

**Comment by barisusakli** [comment]
Yeah keep the backend name as imageClass for now, once you make that change I can merge it. You can keep the label that is displayed in the acp as `Background Image Size`.

**Comment by yariplus** [comment]
Amended

**Pull request merged**
