### PR TITLE
Fix filter:category.build error (double next)

### PR DESCRIPTION
**Pull request by acardinale**

### CODE REVIEW

**Comment by julianlam** [comment]
How did this not crash...

Anyways, can't accept as is because the function below expects `categoryData` only, and if you remove this line, then the `next` needs to be changed so it takes the returned payload and calls `next` with only `err, categoryData`.

**Comment by barisusakli** [comment]
@julianlam  actually it looks good to me cuz it calls data.templateData

**Comment by julianlam** [comment]
Wow, even more confusing. Ok then :laughing:

**Comment by barisusakli** [comment]
Haha yeah, its weird even though there are 2 next calls res.render() was only called once.

@acardinale did this cause a crash for you?

**Comment by acardinale** [comment]
Yes, double aaa crashes.
In a plugin I used filter:category.build and the result was an error (see attached)
nodebb-error

**Pull request merged**
