### PR TITLE
Category: Section

### PR DESCRIPTION
**Pull request by NicolasSiver**
Additional property for Categories:

#### Motivation
Native sections in NodeBB. Most work should be done in templates for theme. By having instruments (checkbox in ACP) and boolean flag, we can create themes with sections on home page (and subcategories) in more convenient way (explicit flag), like this:

- Main
    - General Discussion
    - Programming
    - Events

- Games
    - Actions
    - RPG

#### Look

screen shot 2015-06-18 at 10 09 35 pm

### CODE REVIEW

**Comment by psychobunny** [comment]
@NicolasSiver 
> @psychobunny It's very personal how it should look like. It will be up to you guys, to update default themes (or you could use it only in next default theme). But It's really starting point in creation of Home - Sections and Subcategories - Sections

> My future theme is derived from Persona, so, maybe I could gather changes in PR for Persona in future.

I can merge after a PR to persona and/or lav/vanilla, looks-wise we can always modify it, but doesn't make sense right now to include a feature in core which we don't support outside of third party themes.

The PR looks good though on face value, definitely better solution than my plugin

**Comment by NicolasSiver** [comment]
> I can merge after a PR to persona and/or lav/vanilla

oh...

**Comment by NicolasSiver** [comment]
@psychobunny https://github.com/NodeBB/nodebb-theme-persona/issues/92

**Comment by NicolasSiver** [comment]
> I can merge after a PR to persona

Would be great if you at least consult here - https://github.com/NodeBB/nodebb-theme-persona/issues/92#issuecomment-118088218

**Comment by julianlam** [comment]
Gentle reminder, @psychobunny :smile:

**Comment by NicolasSiver** [comment]
It was long wait ;)
I have checked 0.8 ACP... This pull request is outdated.

**Pull request closed without merging**
