### PR TITLE
set plugin package versions with caret

### PR DESCRIPTION
**Pull request by bonaccorsop**
This could be useful to update patch fixes for all base plugins without changing package.json in NodeBB (this could avoid a lot of commits dependencies)

### CODE REVIEW

**Comment by julianlam** [comment]
Hi there, all other dependencies yes, but bundled plugins are pinned for safety and are automatically updated by Renovate Bot.

**Comment by bonaccorsop** [comment]
Ok, nice to know this

**Comment by bonaccorsop** [comment]
But nodebb-plugin-markdown should be upgraded to 8.8.1 because you haven't upgrade his version after the fix. And the HEAD of NodeBB@master require it with the 8.8.0 version.
In this scenario caret worked for me but if you want to maintain this safety you should do this push in both repos (NodeBB and nodebb-plugin-markdown)

**Comment by julianlam** [comment]
Yes, we'll be publishing the new markdown version shortly.

**Comment by julianlam** [comment]
Versions will remain pinned in NodeBB core.

**Pull request closed without merging**
