### PR TITLE
Allow file uploading on register interstitial

### PR DESCRIPTION
**Pull request by psychobunny**
Requires
https://github.com/NodeBB/nodebb-theme-vanilla/pull/97/
https://github.com/NodeBB/nodebb-theme-persona/pull/433/

### CODE REVIEW

**Comment by pitaj** [comment]
Wait so why are we using jQuery instead of the components module?

**Comment by julianlam** [comment]
components module is actually just a wrapper for jQuery anyways. Might actually be best if we updated components module to use `.querySelectorAll` instead.

**Comment by psychobunny** [comment]
(I pushed that components change to this branch by accident)

**Comment by julianlam** [comment]
LGTM...

**Comment by psychobunny** [comment]
ddffc904f4ec48ac4dce711c9077873101e0a4db

**Pull request closed without merging**
