### PR TITLE
[Add] ForkAwesome

### PR DESCRIPTION
**Pull request by frju365**
Add the ForkAwesome fonts and css. Remove FontAwesome.
ForkAwesome is better for Open Source and free project. It's an only open-source project. FontAwesome has a part free and a part proprietary.

State : Not Finished / Open to discussion.
(Need to remove some icons and add new one)

Website of ForkAwesome : 
https://forkawesome.github.io/Fork-Awesome/

### CODE REVIEW

**Comment by frju365** [comment]
Apparently, I forgot to change something... Let's see what I did wrong.

**Comment by julianlam** [comment]
I've no problem continuing to use FontAwesome, though if there's interest in supporting ForkAwesome then we could remove FontAwesome from core in favour of a plugin-based approach.

Not quite sure how we'd support the premium icons from FontAwesome, though, as I'm assuming they don't want their precious icons published onto npm :smile:

**Comment by frju365** [comment]
Well, I can add just the folder and add a plugin to let the user choose. It's ok for me.

**Comment by djensen47** [comment]
I would be interested in a plugin approach to the font library. Should I open a new issue for that? Ideally it would support multiple icon fonts. For instance, if I create a WWII themed icon font, I wouldn't want to re-invent the wheel for all the other icons.

**Pull request closed without merging**
