### PR TITLE
Send plugin `postData` changes up the line

### PR DESCRIPTION
**Pull request by pitaj**
I change `postData.content` in my plugin's method for this hook. This changes the behavior to the expected behavior which matches that of `filter:post.edit`

### CODE REVIEW

**Comment by julianlam** [comment]
Odd, I would've thought `.fireHook()` would be passing the object _reference_ to the various plugins, and its data would be changed and automatically propagated...

**Comment by barisusakli** [comment]
Hmm that shoulf be the case what was the problem? If post.content is changed in the plugin that should come back from the hook

**Comment by julianlam** [comment]
I'm thinking maybe async clones the returned object...

**Comment by pitaj** [comment]
Yeah I always try to deal with objects as if they are immutable, so I
return a new object and spread the old one in. I use the proposed object
spread syntax like so:

```js
return {
  ...postData,
  content: newContent,
};
```

**Comment by barisusakli** [comment]
@pitaj I think we should revert this change, and you should just modify the actual object passed in and then pass it back to the callback. Doing what you do might break other plugins that run before yours if they add new properties into the postData object.

**Comment by julianlam** [comment]
Yeah, agreed, you should not change the schema of the objects passed in. You can always add new ones, but completely dropping the passed-in object and sending back your own replacement isn't correct and could lead to conflicts with other plugins...

**Comment by pitaj** [comment]
Plugins shouldn't rely on the object being the same reference throughout
the line. It's bad design imo to ever rely on mutability.

**Comment by barisusakli** [comment]
Well the whole point of the filter system is to mutate the postData when it goes through multiple plugins. 

Imagine another plugin adding a new field to postData like `postData.characterCount = postData.content.length`. Now if your plugin runs after this and replaces postData with a new object you are breaking the other plugin.

**Comment by pitaj** [comment]
If I changed the postData content in any way that would break. I'm shallow
copying everything, so any fields they add are copied over.

**Comment by julianlam** [comment]
My worry is that if we make this change then we are setting a precedent that the object we pass in `!==` the object we pass back... in which case we'd have to add these sort of checks every time we fire a plugin hook.

Whereas now the default assumption is you can safely pass in a local var, and _continue using that local var_ later on without having to explicitly define `localVar = returnedVarFromPlugins`

**Pull request merged**
