### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by faddat**
We really should get a docker-compose.yml going.  I know that @Alpacatty had one going a while back.  With docker-compose we can template the entire deployment and allow users to very easily deploy the whole thing, in its full proper form.  Additionally, is this now automatically building in the correct manner?

### CODE REVIEW

**Comment by edasque** [comment]
I have one here that I am happy to adapt and contribute: https://github.com/edasque/docker-nodebb

**Comment by julianlam** [comment]
Either or, whichever you two agree is best, update this PR and will accept :)

**Comment by faddat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Doesn't your docker-compose.yml use the outdated docker image?
(node-ubuntu?)  I did look at it and it's good-- we'd just need to
ensure that it uses the automatically built image tied to the one in
the / of the NodeBB repo and we'd be cooking with gas.

On 1/27/16 8:52 PM, Erik Dasque wrote:
> I have one here that I am happy to adapt and contribute: 
> https://github.com/edasque/docker-nodebb
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/NodeBB/NodeBB/pull/4114#issuecomment-175636529>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWqNJSAAoJEM7qmpGZu/w/iyMP/3IxDd0xZxN8x6nzczJwN2HP
WmeJ2A1weZrdL/u8qPrHeoQj3z22O8FBjs30+JgbP189iPyS6o84Y8GmvsfUw126
LtySPOxoQShAG6SACOkoigTRubzVAxXZIRcLL7mlpTtj5ROFMgjXzeWTVF/gPHdx
i4n24AELgNbXBq5xalr6Upt+FUk3RcYUxuC9+O4lh1Ulb3xjiyLdlR1xGN9DEQQK
/5ZftezEF79SOBCy2T/sWyhLpiF0uPnBBt10ALfpDNpja7KxZyvZDPXbUaICFJGX
N1tGYAs2R0uf0tHzr+R223yK9PdGmbE02PMnZxkjQf0pDI7CtreZSgE2iyvuveIx
poCll3zAjAYlYe16dtSZN0+Vyj2cg18f3S2NsOi3e2ZTethCn0EBSGyet7KeNZzL
lsONWJM8zd4JnUMC+MMaLgsWDobikKwSVaCujh/T8FMQW6BlZ4IEx6w5sCE+4GSq
n3xzUIp4kG8HdMkK7wXmUdoyaTcyCNxn6b/60+1Zhf6mXNb57NWt9CU5116JdfJN
PB2ooxATfzGrlXW+C3o41yB7nzN02ErmWWiv7c+ev8tkVTnalGz7lcsvxN2VlQjB
QK1ANnT3xaboRAgSzS/l5Ruup6tuwRmk1tpYpuBJ+e9HkO0RIt931y/OmONphgss
RN37KchmUNMc9yQhSWkT
=pCXt
-----END PGP SIGNATURE-----

**Comment by faddat** [comment]
@julianlam 

How about we use this opportunity to give NodeBB a docker hub makeover?  We can ensure that the auto-build is built with each push to master, and we can also make sure that the predictable nodebb/nodebb is nodebb-- instead of being nodebb/docker with outdated instructions?  

Nodebb team:

For the steps that require your participation, I'll give detailed instructions.  

@julianlam 

Totally cool with using your docker-compose.yml file with the nodebb/nodebb image that we ensure finally finds its way to docker hub.

**Comment by edasque** [comment]
@faddat , do you want to cooperate on this?

**Comment by faddat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Very much so.  Basically, I want to fix the experience of using docker
for deploying nodeBB and make sure it follows the usual standards and
norms for deploying an app with Docker.  With the compose-file,
Julian's compose file should be totally fine, with the exception that
we should make it so that it uses the (new-- this is the actual goal
of all this hubbub) offical nodebb docker image which will soon be
located at hub.docker.com/nodebb and will be built each time the
master branch is pushed to.  We can also tag releases so that users
can use officially recognized releases instead of getting the latest
revision.  At Klouds we use a system like this to GREATLY accelerate
various dev & deployment processes, and I'm more than happy to share
implementation details if you'd like.

Best,
- -Jake

On 1/27/16 9:27 PM, Erik Dasque wrote:
> @faddat <https://github.com/faddat> , do you want to cooperate on
> this?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/NodeBB/NodeBB/pull/4114#issuecomment-175655677>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWqNVvAAoJEM7qmpGZu/w/62sP/ArQ5n1HXYTFNW1Iq6xw2moK
b3ZlSlDXUYcgds+SU7JRuA5MwVyML141usoU2g8cuVJzxKG4jH/M536lzSOWnH28
EV2KLOUxeE0EbVD1kvJQfqYfwUSCbhT8pItG+vO5lgPnOQ8FzkRmc6oF4kp3WyZE
wt8NSlfIbU8qMJRFrdS4kN0ThVFswgOmYqJ2AK6vS9I9faIQs7Dr7acUTgEmDQgR
GT5qVHtQxHzr9ejvlUrLmcvmDo4vMdu8wrRXtl4cqQa6Ow3fmozC84lavsNlpDIH
kToncPK98A8OqpHEJMYogtk4TAH4njQACUR15RBcrapTLozsyjYsfHhh385XV1Eo
Z9L56QWbnWJKXz3wP/SH/RZ7ZuPhMKgFOA53EvtwjS0dbHzbQ3EFlrIoNcIaDlb1
I86pO5LgA2KYhX0wMWGyhZuYwpw2Hqf28CxVl3XOdKQ+n6eTZUBmS24e4M0qtNCc
MMTKDEYtSzA/HKrakidWqjCASI1PiUYKOgNVCcPBd50eu51AFhO/VI0eBNMD1/GP
XU+4Dk+Raose8sYk7bM8eJgBjI40NfOIlcQOokKMHOAFlC3WWpia8oI3mns6LIev
0qzityeYVnJ+4dSqNXxFEVWR3GwNfu15m9w6tvMjqk1uPYtzl1Tn6OYeLBfCvrgf
a1d6eK2jCJbrtI+7irbb
=tH9+
-----END PGP SIGNATURE-----

**Comment by edasque** [comment]
100% agree, feel free to hit me on https://gitter.im/NodeBB/NodeBB to discuss collaborating on this.

**Comment by faddat** [comment]
@edasque , do you think that we've arrived at a finished product?

**Comment by edasque** [comment]
We have a strategy, I still have to make modifications to the docker.compose file and we have to guide the setup of the nodebb docker hub entry.

**Comment by faddat** [comment]
Sorry, you didn't get the PR?

**Comment by edasque** [comment]
Yes and it needs to be tested. And we have figured out the CMD

**Comment by faddat** [comment]
CMD for which bit?  Are we talking dockerfile CMD or cmd as in

docker-compose up

This actually brings me to another thought.  We should make sure that our docker-compose is handy for folks who have cloned the repo, made some changes and now want to make a quick build & test that out....  I'm thinking more commented-out-lines, you?

**Comment by edasque** [comment]
the Dockerfile command. There is quite a bit left to do before we commit this including testing.

**Comment by faddat** [comment]
@edasque *ping*

What about a Dockerfile CMD again?

**Comment by pitaj** [comment]
#5962 will track this

**Pull request closed without merging**
