### PR TITLE
Update firehook filter:category.update

### PR DESCRIPTION
**Pull request by atomoc**
For example:
```js
var translit = require('transliteration').slugify;


mod.categoryUpdate = function(params, callback) {
	
    if ( params.category.name )
	params.category.slug = params.cid + '/' + translit(params.category.name, {separator: '_'});
	
	
	callback(null, params);
	
};
```

### CODE REVIEW

**Comment by atomoc** [comment]
It may be easier if change the method slugify applying transliteration? :)

**Comment by atomoc** [comment]
Please, look at the PR!

**Comment by barisusakli** [comment]
This can be done using the `filter:category:update` hook.

```
myPlugin.onCategoryUpdate = function(data, callback) {
    data.category.slug = mySlugCreationFunction(data.category.name);
    callback(null, data);
};
```

**Comment by atomoc** [comment]
```js
mod.categoryUpdate = function(categoryData, callback) {
	
	if ( 'slug' in categoryData.category )
	categoryData.category.slug = categoryData.category.slug.split('/')[0] + '/' + translit(categoryData.category.name, {separator: '_'});
	
	
	callback(null, categoryData);
	
};
```

**Comment by atomoc** [comment]
Thanks thanks thanks!

**Pull request closed without merging**
