### PR TITLE
Fix typos in French

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled through [our Transifex project](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

----

*This is an automated message. If you feel this action was in error, please comment on this pull request so it can be looked at again*

**Comment by julianlam** [comment]
@ericgaspar I am not sure whether I can push your changes up to Transifex, but I can try, if you sign the CLA above.

**Comment by ericgaspar** [comment]
> @ericgaspar I am not sure whether I can push your changes up to Transifex, but I can try, if you sign the CLA above.

I am an idiot.... I should have check your translation workflow before pushing my PR... Thanks for your help anyway

**Comment by julianlam** [comment]
It is not your fault — it is not easily discoverable, and so we are looking at options to make it a little easier to see that editing the files directly is not ideal.

Thank you for re-doing your work on Transifex :heart:

**Pull request closed without merging**
