### PR TITLE
fix: replace image urls to absolute when sending notification

### PR DESCRIPTION
**Pull request by cryptoethic**
Hi!

This pr replace image src and a href urls to absolute. It is needed to display them correctly in emails.

Currently when a new topic is created by followed user image is not displayed correctly in email notification.

### CODE REVIEW

**Comment by cryptoethic** [comment]
CLA contains incorrect link to CONTRIBUTING.md file

**Comment by julianlam** [comment]
See if you can attach this to a hook just for emails, as notifications should remain as relative urls

**Comment by cryptoethic** [comment]
I assume it can be done at Emailer.sendToEmail method. But it should be noted that this method is already used by SocketHelpers.sendNotificationToPostOwner.

What do you think about it?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/1e5981c0d6268f1bac381e0f9af81bf953c55189
I added 
```
body = posts.relativeToAbsolute(body, posts.urlRegex);
body = posts.relativeToAbsolute(body, posts.imgRegex);
```
right before sending notification emails.

**Pull request closed without merging**
