### PR TITLE
don't show rooms without messages

### PR DESCRIPTION
**Pull request by pichalite**
don't show rooms without messages in chat dropdown

### CODE REVIEW

**Comment by pichalite** [comment]
yes... no... maybe?

**Comment by barisusakli** [comment]
What is this solving?

User A messaging user B and then deleting that message?

**Comment by pichalite** [comment]
No... User A clicks chat with User B and does not type a message. User B ends up with empty chat rooms in recent list.

**Comment by pichalite** [comment]
this is just a stop gap sort of thing. the proper way to do it is to not add the room to recent chat set for User B until atleast a message is sent

**Comment by nhlpl** [comment]
It's related to: https://github.com/NodeBB/NodeBB/issues/4199

And on big boards it can be an issue.

**Comment by julianlam** [comment]
Hm... can you also update this PR so if you're the last person in a chat room, and that room has 0 messages, then the room is deleted?

**Comment by pichalite** [comment]
@julianlam that should already be taken care of? if there are no messages in the room then the teaser should be empty right?

**Comment by julianlam** [comment]
PR hides the rooms from the list, but doesn't actually delete (or leave, rather) the chat, I think...

**Comment by pichalite** [comment]
no it doesn't delete. what would be the trigger point for the delete? when a user leaves the room?

**Comment by julianlam** [comment]
If a room is orphaned... though you could neuter that to only delete orphaned rooms with 0 messages.

**Pull request merged**
