### PR TITLE
fix: category images (helpers.generateCategoryBackground)

### PR DESCRIPTION
**Pull request by MegaGM**
https://community.nodebb.org/topic/4054/introducing-the-nodebb-0-7-0-persona-preview/63

kinda fix, serverside only.
clientside, I guess, depends on https://github.com/NodeBB/NodeBB/commit/7c7b43d295a61d81249f840e2d69d3de9ad004bb#commitcomment-10424490

### CODE REVIEW

**Comment by MegaGM** [comment]
ping @psychobunny

**Comment by julianlam** [comment]
Weird -- is this still a bug, and what are the repro steps?

**Comment by MegaGM** [comment]
@julianlam Steps? Just set an image for any category. Then open `/categories` (default main route)

```
style="background-image: url(https://i.imgur.com/<anyimage>.png) background-color: #1CAC78; color: #fff;"
```

**Comment by MegaGM** [comment]
> kinda fix, serverside only.

Since the bug with requiring `../utils` was resolved. This fix should work client-side also

**Comment by MegaGM** [comment]
> kinda fix, serverside only.

Since the bug with requiring ../utils was resolved. This fix should work client-side also.

**Comment by psychobunny** [comment]
nice, works. thanks

**Pull request merged**
