### PR TITLE
Use a BCP 47-compliant language tag for Pirate

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by pitaj** [comment]
You can probably achieve the same result by putting `en@pirate` alongside `en_US` in the [`prepareDOM` function in the translator](https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/translator.js#L439)

**Comment by julianlam** [comment]
Looks good to me... what does `en-x-pirate` do anyway in `.toLocaleString()`, one wonders.

image

Not going to lie, was hoping for a `y'arr` or two.

**Comment by julianlam** [comment]
@pitaj brings up a good point in that we are now maintaining two mappings:

* NodeBB/Transifex to timeago (mapping in `translator.js`)
* NodeBB to BCP 47 (currently just the `.replace('_', '-');`)

Prior to merging, I'd like to investigate whether we can eliminate one or the other...

**Comment by BenLubar** [comment]
The timeago locales could be changed into a single JSON file where the keys are looked up via the BCP 47 tag with a fallback to the BCP 47 tag with the first hyphen and everything after it removed.

**Comment by pitaj** [comment]
Yeah there's a lot of things that could be changed with regards to that
method. The best solution is to just rename all NodeBB locales to the
standard format.

**Comment by julianlam** [comment]
Looks like this PR is deprecated in favour of #5218

**Pull request closed without merging**
