### PR TITLE
feat: update to FontAwesome 5.15, resolve #6976

### LINKED ISSUE #6976: Feature Request: Font Awesome 5.5
I just wanted to put in a request to upgrade Font Awesome to version 5.5. Right now it looks like NodeBB v1.10.2 uses Font Awesome 4.7. I just want access to the Discord icon since the login shows a [Pied Piper](https://fontawesome.com/icons/pied-piper?style=brands) icon when using [nodebb-plugins-sso-discord-alt](https://github.com/jsumners/nodebb-plugin-sso-discord-alt) since versions prior to 5.0 do not have the Discord icon.

### PR DESCRIPTION
**Pull request by oplik0**
So, decided to finally try doing it, and it seems to be working out quite well.

As I already mentioned in #6976 a long time ago, while FA5 introduced FA Pro License, that license is NOT required for basic fonts (regular, solid and brands). However, from my understanding the Pro icons and styles (light and duotone) were not present in 4.7 anyway. The Free licenses are the same as they were: CC BY 4.0 for icons, SIL OFL 1.1 for fonts and MIT for code. As required by these licenses, I left the attribution and the licenses along with the files.

There are 2 issues however - while shims do seem to fix most css, plugins that were using less and variables from there that were renamed will break builds. Additionally, the font name changed so if something used `FontAwesome` font in, for example, `:after` element, it just doesn't work.

There is only one example of this in built-in plugins - `nodebb-plugin-composer` uses `@fa-var-arrows-v`, which now is `@fa-var-arrows-alt-v`.
Luckily, [the article on upgrading from v4 to v5](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4) contains a list of all changed icons.  So I quickly converted that list into less variables and deleted the ones that only changed namespace (as it doesn't affect the variables themselves). Additionally, I re-added `FontAwesome` font for compatibility. These changes are all in `nodebb-shims.less` file.

From my understanding there shouldn't really be any incompatibilities now. All current icons are covered via either v4-shims (classes) or nodebb-shims (custom css and less). I haven't tested extensively, but from looking around the site no icon seems missing.

## some additional considerations

So... What about FA6? From current beta changelogs it doesn't seem like much changed. Outside of some CSS/Less/SCSS refactoring it seems the only breaking changes are to Pro icons (duotone mostly). However, currently v6 beta is only available with Pro plan. I'd hope the release doesn't change the free licenses, but who knows - for now, v5 seems to be good enough, and if the next version is released under same licenses it seems like a seamless upgrade will be easy enough.

Another thing to consider is possibility of using npm version of FA, which would allow for easier updates. The issue is that it'd require exposing webfonts folder from `node_modules`, which is why I decided to go the easier route here. Could be an improvement over having to manually update these files though.

Additional idea while things around fonts are being modified would be preloading fonts, but I honestly haven't been working with NodeBB for a rather long time so I don't remember where `<head>` is defined/modified :D I'm not even sure if it will help much (as it feels like FA is used immediately), but Lighthouse complains about lack of preload and it doesn't really cost anything (I really doubt it could decrease performance here), so why not.

### CODE REVIEW

**Comment by psychobunny** [comment]
@oplik0 👍 

noice

**Comment by julianlam** [comment]
@oplik0 the shims file is exactly what we needed, thanks so much for doing this. That was mainly the concern with upgrading (that and the potential licensing issues, if any). If you have looked into it and it looks to be good, then I will trust you :smile: 

> Another thing to consider is possibility of using npm version of FA, which would allow for easier updates. The issue is that it'd require exposing webfonts folder from node_modules, which is why I decided to go the easier route here. Could be an improvement over having to manually update these files though.

Can do post-PR, yes. There *may* have been a reason this wasn't done... perhaps an incompatibility with our requirejs system? Not sure.

> Additional idea while things around fonts are being modified would be preloading fonts, but I honestly haven't been working with NodeBB for a rather long time so I don't remember where <head> is defined/modified :D

Again, we'd appreciate this post-PR. It's rather easy to add a meta or link tag, actually! [Just add it to this file](https://github.com/NodeBB/NodeBB/blob/master/src/meta/tags.js)

**Comment by julianlam** [comment]
Looking at the mgiration guide:

* do we have to update the theme templates to no longer use the `fa` class, but `fas` instead?
* "outline style" is Pro-only, meaning all of the `-o` suffixed icons probably won't work with FA Solid. Is that a problem?

e.g. `flags/detail.tpl`

```
<a class="btn btn-default btn-block" href="#" data-action="assign">
	<i class="fa fa-id-card-o"></i>
	[[flags:assign-to-me]]
</a>
````

**Comment by oplik0** [comment]
1. `v4-shims` handles the old `fa` prefix, including applying correct `font-weight`. While it'd be preferable to change to new prefixes, it's not something that needs to be done.
2. "regular" style is now outline. In general, v5 is more visually consistent with these several styles - while v4 seemed to have some icons outlined and some solid, with a few having two versions (where the `-o` suffix came in), v5 has `regular` as outline, `solid` as, well, solid, and the two pro styles are `light` (outlines, but with smaller lines :) and `duotone`.

As such, the shims actually take all of this into account. For example `fa fa-id-card` and `fa fa-id-card-o` will result in these two icons respectively:
image
Where the solid icon is correctly aliased to `solid` style and the outline is aliased to `regular`.

Unfortunately, that isn't the case with the less shims - as they just alias the actual characters for `content` property - so if some theme or plugin had the icon set up directly in `less` using these variables for `content` it could get the wrong style. The icon will still be correct though.

I quickly made a plugin for checking compatibility: https://github.com/oplik0/nodebb-plugin-fontawesome-test
(just install and enable it, then go to `/fontawesome-test` )

Normal class references work perfectly.
Directly writing symbols in HTML (which I don't think was ever recommended) leaves some broken icons - as I can't really alias them to their changed equivalents there. Hopefully no one uses that method...

Less variables work, but some icons don't get the correct style. However, there doesn't seem to be that significant amount of icons that had distinction between outline/solid style in 4.7, and combined with less variables not being that commonly used (as font awesome classes are the main method after all), I don't think it's a major problem - and it could be mostly written off as part of the visual change in FA (which it kind of is, since regular is, well, the "regular" or default style).

Also, all FA modifiers, including the animations, size changes etc. seem to work just fine.

**Comment by julianlam** [comment]
Then LGTM. Will merge tomorrow or Wednesday 😁

**Comment by psychobunny** [comment]
@oplik0 thanks! and your shim was an amazing idea

**Comment by psychobunny** [comment]
I'm adding a breaking tag, just in case. I need to go through most of our custom themes for clients to double check before an official release but def should be in for 1.8.0 either way :)

**Comment by oplik0** [comment]
I agree with these tags, especially as the change can technically result in different icons (as I mentioned, less variables have no awareness of original style - so if someone was using a less variable to get a solid icon they might get an outlined one).
I don't think it's a big issue - not only does this way of using FA seem rare, but instances where this would matter in any way would be even rarer - but it's still a change that can cause different behavior from previous versions.

**Pull request merged**
