### PR TITLE
plugin-topic-events needs uid on action:topic.delete

### PR DESCRIPTION
**Pull request by rbeer**
Since topic-events stores the user deleting a topic, it needs the uid passed on hook [action:topic.delete](https://github.com/NodeBB/NodeBB/blob/master/src/threadTools.js#L42).
https://community.nodebb.org/topic/2115/topic-events-plugin

### CODE REVIEW

**Comment by rbeer** [comment]
Sadly, this would break other plugins, such as plugin-dbsearch.

**Comment by julianlam** [comment]
Thanks @rbeer . You'll need to submit PRs for solr and elasticsearch plugins as well :smile:

**Comment by rbeer** [comment]
@julianlam 
Is there any chance, those hook handlers
```json
{ "hook": "action:topic.delete", "method": "topic.delete"},
```
```js
Elasticsearch.topic.delete = function(tid) {
	if (!parseInt(Elasticsearch.config.enabled, 10)) {
		return;
	}

	Elasticsearch.deindexTopic(tid);
};
```
are called from outside of the plugins?

```js
var tid = (void 0 === topicObject.tid) ? topicObj : topicObj.tid;
```
might be a safer solution than simple replacement, then.

**Comment by rbeer** [comment]
uhh. this was bad. Is there a way to return or exclude this merge commit?
Sorry :/

**Comment by julianlam** [comment]
Don't bother doing a merge commit, rebase instead :) 

For now just start a new pull request. You'll probably want to make the changes on a new branch.

**Pull request closed without merging**
