### PR TITLE
Starting post incorrectly links to admin panel

### PR DESCRIPTION
**Pull request by trigun0x2**
It was linking relatively to the current url which gave an error on my site.

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @trigun0x2, I can't merge this because it doesn't work with subfolder installations. It needs to be relative, so I'll have to take a look at why it doesn't work. Perhaps just adding another `../` is enough.

**Comment by trigun0x2** [comment]
@julianlam ah, totally forgot about that. I'm sure you can just get the ```nodeBB_base_url + /admin```?

**Comment by julianlam** [comment]
@trigun0x2 I can't reproduce this on my dev environment. When I configure a subfolder installation (`/forum`), it links to `/forum/admin`. When I configure a regular install (subdomain-style), it links to `/admin`.

Under what circumstances is this happening, and what is your `config.json`'s `url` value?

**Comment by trigun0x2** [comment]
Hey Julian, I realized that the get started page online links to the v0.60
branch. And that's the release I launched which has this issue. Maybe it
has been fixed already.

**Comment by julianlam** [comment]
Quite possibly :smile: Thanks for submitting the pull request though!

**Pull request closed without merging**
