### PR TITLE
Upvote notifications

### PR DESCRIPTION
**Pull request by boomzillawtf**
Allow users to adjust how many notifications they get for upvoted posts:
- All (current behavior)
- 1st, 5th, 10th, multiples of 50
- First only
- None

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
I'm not sure what's happening with that build for node 4.1. the builds for 4.0 and 4.2 pass, and looking at your changes i don't see anything obvious that would affect the tests that failed. So i'm tempted to say it's a transitory build error and something odd happened with mongo there... 

perhaps one of the nodebb devs will be able to better diagnose

**Comment by julianlam** [comment]
My main concern is that if this option is set, it may cause users to miss being notified if the option is set to "First".

**Comment by boomzillawtf** [comment]
How so? They should still get the first notification.

**Comment by julianlam** [comment]
They would, but if they read the topic and later on received another notification, would they be notified again?

**Comment by boomzillawtf** [comment]
The would only receive a notification for the first upvote on that _post_. They'd still get upvote notifications for other posts. But they said they only wanted the first upvote notification per post, so that's all they'd get.

**Comment by yamikuronue** [comment]
Our instance has been using this functionality for months now, and I haven't seen any bug reports since shortly after it was developed. Is this going to be merged?

**Comment by boomzillawtf** [comment]
It was turned into a plugin:
https://github.com/boomzillawtf/nodebb-plugin-upvote-notifications

**Comment by pitaj** [comment]
#5963

**Pull request closed without merging**
