### PR TITLE
Use npm instead of vendor files

### PR DESCRIPTION
**Pull request by pitaj**

### CODE REVIEW

**Comment by julianlam** [comment]
Thanks, LGTM. For future reference, where do the module files have to live if you want to `require(['ace/ace'], function (ace) { ... });`, for example?

I see you added the `ace-builds` package, but don't see how it ties to `ace/ace`

**Comment by pitaj** [comment]
The files are copied into `build/public/src/modules` just like the other modules. 

https://github.com/NodeBB/NodeBB/blob/b53d3254dde7f43544ba08652801b22a89b73dd6/src/meta/js.js#L91

**Comment by julianlam** [comment]
Thanks @pitaj

**Comment by margussipria** [comment]
Even though this is closed just noticed, this increased docker image size 😆 

```
+3.4M	node_modules/zxcvbn # not part of this pull request
+39.5M	node_modules/ace-builds
+2.5M	node_modules/bootstrap

-98.5M	node_modules
+144.0M	node_modules
```

**Comment by pichalite** [comment]
Yes coz those node modules come with a bunch of stuff that NodeBB doesn't need. Source files, demos...

**Comment by pitaj** [comment]
If you want to save space you can delete everything except for `src-min` and `package.json` inside `node_modules/ace-builds`. In fact, if you aren't planning on building static assets at all inside the docker image, you can delete a lot of `node_modules`.

**Pull request merged**
