### PR TITLE
Add fireHook filter:topic.create

### PR DESCRIPTION
**Pull request by atomoc**
Example:
```js
var translit = require('transliteration').slugify;


mod.topicCreate = function(data, callback) {

	data.slug = translit(data.title, {separator: '_'});


	callback(null, data);

};
```

### CODE REVIEW

**Comment by julianlam** [comment]
@atomoc, please use `filter:topic.post` hook instead

**Comment by atomoc** [comment]
> @atomoc, please use filter:topic.post hook instead

Sorry, are you kidding me? You are disturbing me more than help, why?

**Comment by atomoc** [comment]
In your place I would have already implemented a transliteration in the core. Why not?

**Comment by julianlam** [comment]
The `filter:topic.post` hook is better suited. `Topic.create` is an internal method. If you're running a fork with the transliterated topics, then keep on using it.

**Comment by atomoc** [comment]
I do not understand you. You recommend me used fork? I have more 10 similar forks, and with each update conflicts arise.

**Pull request closed without merging**
