### PR TITLE
Loading manifest failed with 404 when deploying basic auth, add cross…

### PR DESCRIPTION
**Pull request by corbolais**
…origin use-credentials.

See also:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
https://stackoverflow.com/questions/40985833/is-it-possible-to-load-the-progressive-web-app-manifest-file-from-authenticated

Signed-off-by: corbolais <corbolais@gmail.com>

### CODE REVIEW

**Comment by psychobunny** [comment]
haven't looked yet, but wow thanks for the PR!

**Comment by corbolais** [comment]
Hey,
won't sign such a prohibitive Contributor License Agreement but feel free to incorporate the one-liner by yourself.
thx

**Comment by psychobunny** [comment]
If you have an issue with our CLA, you can open an issue on our GH. We just did it as a standard thing to cover ourselves; happy to revisit.

**Comment by psychobunny** [comment]
But thank you! :)

**Pull request closed without merging**
