### PR TITLE
feat(email): don't escape html in notification bodies.

### LINKED ISSUE #7034: email notification has no formatting
image

Just blob of text and hard to read.

Original post 

image

### PR DESCRIPTION
**Pull request by tcmal**
Allows for post replies, etc. to show the formatting of the original post, rather than looking garbled.

Closes #7034, see screenshots there.

### CODE REVIEW

**Comment by pitaj** [comment]
@barisusakli it looks like you made the change in c839d1cbc0abde6944975ee71d6a6b5894b735d2 which was meant to fix #6080 and #6078. It doesn't appear to be because of any kind of security concern.

**Comment by barisusakli** [comment]
Gotto think about the case where the forum doesnt have markdown plugin and using for example html-sanitize plugin. Is bodyLong going through those hooks 🤔

**Comment by tcmal** [comment]
I believe it goes through the same processing posts go to when they're sent to an actual client, which then doesn't process it any further.

**Comment by barisusakli** [comment]
Looking through the code that is not always the case, maybe if `bodyLong` is set to `postData.content` that is true but there are other cases where bodyLong is just a language string.

The flow is usually like this; 

```
var data = {
   // .. some other data
   bodyLong: 'can be any string',
};
notifications.create(data, function (err, notif) {
    if (notif) {
          notifications.push(notif, uids, callback);
    }
});
```

**Comment by barisusakli** [comment]
What if we call utils.escapeHtml on bodyLong 🤔

**Comment by pitaj** [comment]
Email clients do their own sanitizing. I'm not saying we shouldn't do it as well, but it's not super important.

**Comment by julianlam** [comment]
@pitaj approved offline :+1:

**Pull request merged**
