### PR TITLE
Fix admin Search

### PR DESCRIPTION
**Pull request by RoiEXLab**
This edits the href attribute to match the db-search route...

### CODE REVIEW

**Comment by julianlam** [comment]
ACP search isn't the same as db search... unless I am mistaken...?

**Comment by RoiEXLab** [comment]
Correct, but the admin panel offers to "search the forum" if a search Plugin is enabled...
Currently using this feature leads to a 404 error

**Comment by pitaj** [comment]
@julian ACP search has a "search forum instead" function IIRC

**Comment by julianlam** [comment]
Okay, waiting on your review then @pitaj 👍

**Comment by RoiEXLab** [comment]
@julianlam @barisusakli Just a quick reminder, that this PR is ready to be merged...

**Pull request merged**
