### PR TITLE
Better fix for #5993

### LINKED ISSUE #5993: If a custom home page is set in the ACP (General -> Homepage), page is redirected, not directly rendered
e.g. if I set the home page to `/user/admin`, then navigating to my forum at http://localhost/forum will redirect me to http://localhost/forum/user/admin.

This doesn't happen if I set the homepage to a non-custom option, like "Recent". Not sure if this is too difficult to resolve for custom pages?

### PR DESCRIPTION
**Pull request by pitaj**
Also a nice newline so the line doesn't get overwritten when running `./nodebb upgrade`

### CODE REVIEW

**Comment by barisusakli** [comment]
test is failing, also does this work for plugin added routes?
```
//in plugin
data.router.get('/test1', function (req, res, next) {
	res.send('123');
});
```
then set custom route as `test1` I get 404 instead of the page.

**Comment by pitaj** [comment]
@barisusakli alright I've fixed those issues and added some optimizations. It should be faster than ever before.

**Comment by barisusakli** [comment]
@pitaj getRoute is undefined until a config is updated
```
 TypeError: getRoute is not a function
    at module.exports (C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\src\controllers\home.js:44:2)
    at Layer.handle [as handle_request] (C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\express\lib\router\index.js:335:12)
    at Immediate.next (C:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\express\lib\router\index.js:275:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by pitaj** [comment]
Just fixed that.

**Pull request merged**
