### PR TITLE
Fix eslint rules

### PR DESCRIPTION
**Pull request by HeeL**
Fixed following rules:
- space-before-blocks: enforce consistent spacing before blocks
- semi: require or disallow semicolons instead of ASI
- semi-spacing: enforce consistent spacing before and after semicolons
- no-undef-init: disallow initializing variables to undefined

### CODE REVIEW

**Comment by HeeL** [comment]
I've just rebased it with master. Tests failing on Travis because new controller tests use nconf.get('url') that return undefined.  You have to define it in some config for travis

**Comment by HeeL** [comment]
@julianlam I've rebased to master and fix problems with functional tests. Can you please merge this before something new popup? There are lot of changes in here

**Comment by julianlam** [comment]
Sure.

Your `function(` rule is causing us much grief 😅

**Comment by pichalite** [comment]
get rid of that damn thing :smile:

**Comment by HeeL** [comment]
Its not my, its Airbnb ;)

Am 25.10.2016 9:35 nachm. schrieb "Julian Lam" <notifications@github.com>:

**Comment by julianlam** [comment]
@pichalite @psychobunny can't argue with that logic :shipit:

**Comment by pichalite** [comment]
Well just coz we are using Airbnb rules spec doesn't mean we have to use it 100% as is.

**Comment by HeeL** [comment]
I think its important to stay consistent with code style and not that important to have or not to have a space after function keyword. Feel free to make a PR that change this. I have a separate commit for each rule, so it will be a matter of revert

**Pull request merged**
