### PR TITLE
Additional Creational filters

### PR DESCRIPTION
**Pull request by NicolasSiver**
Added 2 new creational filters for Category and Topic entities.

- `filter:topic.create`
- `filter:category.create`

### Motivation

Need additional filters, so plugin can have impact on creation of mentioned entities. Working on [Plugin for Slugs](https://github.com/NicolasSiver/nodebb-plugin-ns-slugify)

I will appreciate fast Merge. thanks ;)

### CODE REVIEW

**Comment by barisusakli** [comment]
Check out https://github.com/NodeBB/NodeBB/commit/5445e32522190d83e378e9bd6b5d11b0ab4d1603

Main changes are the hooks receive the data in an object so we can add more stuff in the future without breaking old plugins. So
`plugins.fireHook('filter:category.create', {category: category}, next);`
and
`plugins.fireHook('filter:topic.create', {topic: topic}, next);`

I also changed it to use the current waterfall syntax.

**Comment by NicolasSiver** [comment]
Good. Could you check also - https://github.com/NodeBB/NodeBB/pull/3243 ?

**Comment by barisusakli** [comment]
@psychobunny said he wants to take a look at that. He already has a plugin that does something similar. https://github.com/NodeBB/nodebb-plugin-category-sections but it is kind of a hack.

**Comment by psychobunny** [comment]
@NicolasSiver is there a PR incoming for the default themes as well?

**Comment by NicolasSiver** [comment]
@psychobunny It's _very personal_ how it should look like. It will be up to you guys, to update default themes (or you could use it only in next default theme). But It's really starting point in creation of `Home - Sections` and `Subcategories - Sections`

My future theme is derived from Persona, so, maybe I could gather changes in PR for Persona in future.

**Comment by psychobunny** [comment]
(Continuing discussion in #3243)

**Pull request closed without merging**
