### PR TITLE
Fix favicon and touch-icon paths

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
Fixes the favicon path of where the favicon is actually saved. 

Gets rid of this warning:
[deprecated] Accessing `favicon.ico` from `/` is deprecated to be REMOVED in NodeBB v1.7.0. Use `/assets/favicon.ico` to access this file.

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Pull requests need to be made against either `master` or `develop`. It looks like this pull request was made against a version branch and should not be merged. Please comment if you feel that this is in error.

Thanks!

**Comment by julianlam** [comment]
Hi @sebastian-marinescu -- this is good, though two things:

1. Can you make this against `master`
1. Can you use `nconf.get('upload_path') + '/system'` instead, as that is better than hardcoding the route.

**Comment by julianlam** [comment]
@sebastian-marinescu I just re-based this against `master`, so just take a look at #2 when you have a chance, thanks!

**Comment by sebastian-marinescu** [comment]
Hi @julianlam, thanks for reacting so fast. 
I updated the path - did you mean it like that?

**Comment by julianlam** [comment]
@sebastian-marinescu Almost!

I was mistaken, it is `nconf.get('upload_url');`, not `upload_path`

**Comment by sebastian-marinescu** [comment]
Check, fixed!

**Comment by sebastian-marinescu** [comment]
Looking at the code again, it seems that "apple-touch-icon" (without extension) is also not correct. 
In the ACP and in the uploadTouchIcon method it saves it as "touchicon-orig.png". 
Should I also fix it?

**Comment by julianlam** [comment]
I can't actually get this error to show up in current code (without your patch)...

**Comment by sebastian-marinescu** [comment]
Uh oh, what have I done? How can I revert the last weird merge?

**Comment by sebastian-marinescu** [comment]
Nevermind...

**Comment by pitaj** [comment]
To fix the weird merge issue, I'd do the following:
```
git fetch
git checkout -b temp-patch-2
git reset --hard origin/master
git cherry-pick 9a2df2b5c5e588913fe1956556acaecabb190946
```

**Comment by julianlam** [comment]
Better late than never :smile:

**Pull request closed without merging**
