### PR TITLE
corrections/translations/improvements and removal of possessive prono…

### PR DESCRIPTION
**Pull request by robjens**
Ik took the liberty of employing a range of corrections/changes to terms, grammar, spelling, consistence, possessive pronoun use (formal case `u`, `uw` and verbs, as well as casual one `je`, `jouw`) to imperative forms. Not perfect yet but a lot better, some errors were ... erh, painful :D

### CODE REVIEW

**Comment by julianlam** [comment]
Hello there @robjens!

We actually handle all of our translation efforts on our [Transifex Project](//transifex.com/projects/p/nodebb/), so if possible, please add your work there and I can pull it in in a single command :smile:

**Comment by julianlam** [comment]
Oh, and "customize" is American, whereas "customise" is Canadian/British, hence we use the `s` :smile:

**Comment by robjens** [comment]
Right. I should close this anyway, screwed up on my end with renaming something so please discard and I'll move my things in at Transifex... Really... I never knew that customise was one of those forms. Pardom my bad :P

**Comment by julianlam** [comment]
> I never knew that customise was one of those forms.

I'm probably just being a pedant. Most likely the majority of Canadians are heavily influenced by American English and switch to using the `z` variant. They apply to all words with the `-ise/-ize` suffix, like "equalise" and "dramatise".

Most Canadian I meet still use the extra `u` in `neighbour`, however, so that isn't going away any time soon...

**Comment by robjens** [comment]
I once was commander of a online game alliance (for this text-based kingdom strategy game) called `Honour and Justice` ... erh, so yeah, lol I kinda know ;)

**Pull request closed without merging**
