### PR TITLE
Add 'load more' button to topic list

### PR DESCRIPTION
**Pull request by rbeer**
That does it! This was like the 4th time I went all nuts, 'cause I thought one of my plugins broke the topic listing. :laughing: 
example

### CODE REVIEW

**Comment by barisusakli** [comment]
Can you explain what's going on here and why you need the load more button?

**Comment by rbeer** [comment]
Hi @barisusakli
> Can you explain what's going on here and why you need the load more button?

Sure can. :smiley:

Steps to reproduce:
- Fill a category with some topics (10-20)
- Set user's Settings/Pagination/'Topics per Page' value to a rather small number, like 5
- Maximize browser window (height is the important property)
- Visit category's route and you'll end up with something like the picture shows.

Problem:
While the 'scroll' event is hooked correctly, it's never triggered, since the backend acknowledges user's setting (as expected) and only sends (e.g.) 5 topics to show. As the viewport is bigger than body's height, there's no way to scroll (i.e. trigger the handler to load more topics). With the one exception of re-sizing the window, of course.

Come to giving it some fresh thought's, though, I never had any users complain about this, so it might be a case of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). :innocent:

**Comment by julianlam** [comment]
Yeah it's typically a YAGNI thing, we've been aware of it, although it only occurs when posts per page or topics per page is set arbitrarily low :smile:

**Comment by rbeer** [comment]
@barisusakli @julianlam
Alright then; I'll just close the PR, but let the branch sit in my fork, in case this ever becomes a real issue. 4K screens are coming, after all. :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
