### PR TITLE
Fixing spelling issue

### PR DESCRIPTION
**Pull request by DomLennonZA**
Fixing a spelling issue that causes the wrong callback to be invoked
when deleting a user.

### CODE REVIEW

**Comment by barisusakli** [comment]
Will merge once CLA is signed.

**Comment by DomLennonZA** [comment]
I am signing the CLA but its just coming back to this page and its not saying its signed?

**Comment by barisusakli** [comment]
Hmm not sure. What about athenauser seems like the commit is from there

**Comment by DomLennonZA** [comment]
No idea why its using that alias? I cant actually sign in with that. If it helps, you could just take the change and commit it yourself? I dont really mind.

**Comment by barisusakli** [comment]
Ok I made the change myself, thanks for the PR.

**Pull request closed without merging**
