### PR TITLE
Fix for DE localization

### PR DESCRIPTION
**Pull request by alexschomb**

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @alexschomb, please make these changes to our Transifex repository, thanks!

**Comment by julianlam** [comment]
https://www.transifex.com/projects/p/nodebb/

**Comment by alexschomb** [comment]
Oops. Sorry, didn't know about that. Thanks!

**Comment by alexschomb** [comment]
What should I do if the new strings chat.mark_all_read and scroll_to_my_post are not available in the Transifex project?

**Comment by julianlam** [comment]
I can push those strings up for you in the morning :)

**Comment by julianlam** [comment]
@alexschomb The latest language keys have been pushed to transifex.

**Comment by bopjesvla** [comment]
`global.views` still isn't available.

**Comment by julianlam** [comment]
@bopjesvla Hi there, from what I can tell, the resource is available on Transifex.

selection_039

**Pull request closed without merging**
