### PR TITLE
Add notification frequencies from nodebb-plugin-upvote-notifications.

### PR DESCRIPTION
**Pull request by BenLubar**
https://github.com/boomzillawtf/nodebb-plugin-upvote-notifications

### CODE REVIEW

**Comment by pitaj** [comment]
I think having both `logarithmic` and `threshold` is a little redundant. What if we made the behavior of logarithmic closer to what threshold does, by changing it like so:

    return votes > 0 && (Math.log10(votes) % 1 === 0 || Math.log10(votes / 5) % 1 === 0);

That would result in 1, 5, 10, 50, 100, 500, etc, which is close to the threshold behavior.

**Comment by machado2** [comment]
I'd like it to start at 5, or 10. Or maybe we should be able to use our own list.

The first vote isn't worth of a notification. There is even a guy using upvotes to mark posts as read in a forum I use.

**Comment by loopback0** [comment]
After 50 it doesn't really matter, and certainly not after 100, but I like having something between 10 and 50.

**Comment by pauljherring** [comment]
> The first vote isn't worth of a notification.

Really?

> There is even a guy using upvotes to mark posts as read in a forum I use.

So when 5, or 10, people do that, are you proposing to remove those notifications for other forums as well? 

Thought not. 

That user needs a word in his shell-like, not working around in software.

> Or maybe we should be able to use our own list.

Or 
- default list which can be overridden by
- site list which can be overridden by
- user's own list.

One thing I'm particularly against is trying to be cute with stuff like this however:

> `return votes > 0 && (Math.log10(votes) % 1 === 0 || Math.log10(votes / 5) % 1 === 0);`

That's the sort of thing that ends up on our front page...

**Comment by pitaj** [comment]
@pauljherring how else would one check if a number is a power of ten, or 5x a power of ten?

**Comment by pauljherring** [comment]
> how else would one efficiently check if a number is a power of ten, or 5x a power of ten?

I'd go for bit-twiddling, to check  for powers of 2, and 2 times powers of two....

**Pull request merged**
