### PR TITLE
Add plugin hook to category controller

### PR DESCRIPTION
**Pull request by PWesterdale**
This allows the user to hook into the category controller

### CODE REVIEW

**Comment by barisusakli** [comment]
What are you using the hook for? Maybe one of the existing hooks already covers your use case.

For example `filter:category.get` or `filter:category.build`

**Comment by PWesterdale** [comment]
I had been using the controller hook for topic to output some variables to the template dependant on the topic category ID. I also needed to do something similar on the category route and after looking in the controller could not find a hook.
Although I can alter my code to use one of the other hooks, for the sakes of readability and conforming to a standard I'd suggest this PR still has merit.

**Comment by barisusakli** [comment]
Well we added the `filter:<template>.build` hooks just for this use case. There is one for every route nodebb has ie `filter:topic.build`, `filter:category.build`, `filter:recent.build` etc.

`filter:controllers.topic.get` was probably added before we had the `filter:<template>.build` family of hooks.

So the standard is actually `filter:<template>.build` now.

We recently added `filter:middleware.render` as well which gets called on all pages, so you can add extra data to all routes.

**Comment by PWesterdale** [comment]
No problem, I'm working on a legacy version that didn't have these hooks and has strayed a little away from source.
We are working to bring it into line so we can get back on mainline, as such some of these hooks are not available to me yet!

Sorry for the time-waste!

**Comment by barisusakli** [comment]
No worries, let us know if you run into issues upgrading. You can post on https://community.nodebb.org for help as well.

**Pull request closed without merging**
