### PR TITLE
disable `io` cookie

### LINKED ISSUE #7947: Disable socket.io io cookie
It turns out that this cookie isn't actually used for anything:
https://github.com/socketio/socket.io/issues/2276
It's basically an useless, non-secure cookie that can be easily disabled.

### PR DESCRIPTION
**Pull request by oplik0**
Decided to actually do it myself after seeing how trivial it it :D
Closes #7947

### CODE REVIEW

**Comment by barisusakli** [comment]
Lol I beat you to it 😆

**Comment by oplik0** [comment]
Oh, @barisusakli beat me to it :D

**Comment by oplik0** [comment]
Again :D

**Comment by barisusakli** [comment]
Thanks for reporting 👍

**Pull request closed without merging**
