### PR TITLE
Adding missing packages from packages.json

### PR DESCRIPTION
**Pull request by malixsys**

### CODE REVIEW

**Comment by julianlam** [comment]
These packages are not missing from NodeBB, we do not use them in core?

**Comment by malixsys** [comment]
When running through setup, it blows up...

**Comment by julianlam** [comment]
On which OS? Setup completes properly on Ubuntu 14.04, which is our testing base.

**Comment by NukeRusich** [comment]
I have not seen any of these dependencies on my Windows dev machine or my SmartOS test machine.

**Pull request closed without merging**
