### PR TITLE
Ignore topic

### PR DESCRIPTION
**Pull request by boomzillawtf**
Changes the current Watching / Ignoring topic settings into:

* Watching: Shows up in unread, notifications whenever a post is made, gets other normal notifications (upvote, mentioned)
* Reading: Shows up in unread, gets normal notifications
* Ignoring: Never displayed as unread, either in the unread list or styled as unread in other topic lists. User receives no notifications from this thread.

Related PRs in persona, vanilla themes.
https://github.com/NodeBB/nodebb-theme-vanilla/pull/76
https://github.com/NodeBB/nodebb-theme-persona/pull/271

### CODE REVIEW

**Comment by julianlam** [comment]
Can you remove the changes to `public/languages` that aren't in `en_GB`? We have to pull those in from Transifex :smile:

**Comment by boomzillawtf** [comment]
Oops...removed.

**Comment by boomzillawtf** [comment]
The CI failure looks like a CI server problem:
```
The command "sudo apt-get install mongodb-org-server" failed and exited with 100 during .
```

**Comment by boomzillawtf** [comment]
This one is getting stale. Are you guys interested in this? I'm still interested in moving forward with this and certainly open to suggestions or whatever.

**Comment by julianlam** [comment]
Thanks for following up... I believe internally we are concerned that the function of the various states are not intuitive to first time users...

**Comment by barisusakli** [comment]
I am working on this in a branch https://github.com/NodeBB/NodeBB/tree/topic-watching

**Pull request closed without merging**
