### PR TITLE
Language control

### PR DESCRIPTION
**Pull request by atomoc**

### CODE REVIEW

**Comment by julianlam** [comment]
Hi @atomoc -- translations are handled on [our Transifex project](https://transifex.com/projects/p/nodebb/), instead of via pull request, so you can make your changes there :smile:

**Comment by julianlam** [comment]
To add *new* language strings, you'll need to add the corresponding English language string into `en_GB` first, then we can push it to Transifex.

**Comment by julianlam** [comment]
We can merge English+Russian at the same time, but this is pending nodebb/nodebb-theme-persona#40 as well

**Comment by atomoc** [comment]
I do not understand why add rows in en_GB if I have a default value in the English language.

**Comment by atomoc** [comment]
[[category:no_posts:**No new posts.**]]

**Comment by atomoc** [comment]
Understood to add these lines to Transifex. Okay!

**Comment by atomoc** [comment]
I can hardly imagine working with Transifex...

**Comment by julianlam** [comment]
`<p class="cat-title">[[category:cat_title:Categories]]</p>` This is not how it should be written in the template. Will comment further in the commit itself. :smile:

**Comment by julianlam** [comment]
@atomoc Please handle all translations on Transifex. Thanks :smile:

**Comment by atomoc** [comment]
Ok, as I understand immediately do :)

**Pull request closed without merging**
