### PR TITLE
added missing translation in dashboard

### PR DESCRIPTION
**Pull request by Pappmann**
added missing translations in dashboard.js

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled through [our Transifex project](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

----

*This is an automated message. If you feel this action was in error, please comment on this pull request so it can be looked at again*

**Comment by Pappmann** [comment]
i dont understand, how can i add some missing implemented language strings via transifex???

I changed the nodebb/src/controllers/admin/dashboard.js

**Comment by pitaj** [comment]
You're only supposed to add language strings to the `en-GB` version. If you don't mind, can you remove the other copies? Thanks.

**Comment by Pappmann** [comment]
I understand, i cant delete the copies in this pull request.

**Comment by pitaj** [comment]
> i cant delete the copies in this pull request

Why not?

**Comment by Pappmann** [comment]
i dont know how to do that.

**Comment by pitaj** [comment]
Okay, well you can close this PR and open a new one, then?

**Comment by Pappmann** [comment]
yes

**Comment by pitaj** [comment]
Thank you!

**Pull request closed without merging**
