### PR TITLE
Add fireHook filter:category.create

### PR DESCRIPTION
**Pull request by atomoc**
Example for, translit slug:
```js
var translit = require('transliteration').slugify;


mod.categoryCreate = function(params, callback) {
	
	params.slug = translit(params.name, {separator: '_'});
	
	
	callback(null, params);
	
};
```

### CODE REVIEW

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/5445e32522190d83e378e9bd6b5d11b0ab4d1603

**Comment by atomoc** [comment]
https://github.com/NodeBB/NodeBB/commit/5445e32522190d83e378e9bd6b5d11b0ab4d1603#diff-ed75d775004d7f6bf533c07c815c33abR27
How I can translit slug if not data.slug in the line?

**Comment by barisusakli** [comment]
You can use the new hook `filter:category.create`

A small example in your plugin

```
myPlugin.onCategoryCreate(data, callback) {
    data.slug = data.category.cid + '/new-slug';
    callback(null, data);
};
```

That should work I think.

**Comment by atomoc** [comment]
Good, thanks!

**Pull request closed without merging**
