### PR TITLE
adding filter:login.check and loginFormEntry[] for the filter:login.build hook

### PR DESCRIPTION
**Pull request by akhoury**
related to https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/32

### CODE REVIEW

**Comment by akhoury** [comment]
We use 2 hooks for this `filter:login.build` to display the captcha, and `filter:login.check` to check the captcha after the POST request is done.

**Comment by akhoury** [comment]
similar to `filter:register.check` https://github.com/NodeBB/NodeBB/blob/603c5262876a8e8be16d0587424179ed18d6955a/src/controllers/authentication.js#L61

**Comment by julianlam** [comment]
Fixed conflict, checking tests

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/pull/490

**Pull request merged**
