### PR TITLE
isMain on topic.create for filter:post.create

### PR DESCRIPTION
**Pull request by pitaj**
Right now there's no way to tell if the post passed to `filter:post.create` is the main post of a topic.

### CODE REVIEW

**Comment by pitaj** [comment]
@barisusakli

**Comment by barisusakli** [comment]
What about old posts, they won't have `isMain` field.

**Comment by pitaj** [comment]
True, but you can check old posts by getting the `mainPid` field of their topic and checking it against their `pid`.

**Comment by barisusakli** [comment]
If you just need to know `isMain` in the hook then maybe it's better not to save it in the post hash then.

>postData.isMain = true;
>posts.create(postData, next);

Just having that should be enough for plugins?

**Comment by pitaj** [comment]
Nope. A different object gets passed to those hooks, which requires the changes I made in the other file.

**Comment by barisusakli** [comment]
>plugins.fireHook('filter:post.create', {post: postData, data: data}, next);

This is passed to plugins, `data` will have `isMain` no?

**Comment by pitaj** [comment]
Look at line 36. postData is redefined as a new object before that hook is called.

**Comment by barisusakli** [comment]
I am talking about `data` not `postData`. In the plugin you can check that.

```
myPlugin.onPostCreate = function(hookData, callback) { 
    if (hookData.data.isMain) { 
         //this post is main post
    }
    callback(null, hookData);
};
```

**Comment by pitaj** [comment]
Oh. Yeah, you're right. My bad. I'll reset that file then. Unless you just want to add that one line to core instead of going through this PR.

**Comment by barisusakli** [comment]
You can make the change, I'll merge.

**Comment by pitaj** [comment]
Okay change made

**Pull request merged**
