### PR TITLE
add missing translation in groups

### PR DESCRIPTION
**Pull request by pichalite**

### CODE REVIEW

**Comment by julianlam** [comment]
Hm, I thought bootbox automatically translated?

**Comment by pichalite** [comment]
it does? I don't see it anywhere.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/public/src/overrides.js#L105

**Comment by pichalite** [comment]
well looks like it's not working then?

**Comment by julianlam** [comment]
Depends... what's not being translated, the modal content, or the success/cancel buttons?

**Comment by pichalite** [comment]
modal title

**Comment by julianlam** [comment]
Yeah, for a `bootbox.prompt`, it's definitely related to `overrideBootbox` then, as the prompt itself has a predefined title that we've internationalised...

**Comment by pichalite** [comment]
OK I see the actual issue now. The issue was a typo, `group` instead of `groups`. Translator not required in this case. Updated the PR.

**Comment by julianlam** [comment]
Thanks :smile:

**Pull request merged**
