### PR TITLE
new filter hooks on favourite actions #2620

### PR DESCRIPTION
**Pull request by TheBronx**
before a favourite action is made, fire a filter hook so plugins can
modify or cancel that action before it takes place.

### CODE REVIEW

**Comment by barisusakli** [comment]
You should probably do 

`plugins.fireHook('filter:post.' + command, {data: data, uid: socket.uid}, function(err, filteredData) {`

So you have access to the person who is doing the action.

**Comment by TheBronx** [comment]
you are right @barisusakli, I've updated the pull request

**Comment by barisusakli** [comment]
Need to change this as well

`executeFavouriteCommand(socket, command, eventName, notification, filteredData, callback);`

to 

`executeFavouriteCommand(socket, command, eventName, notification, filteredData.data, callback);`

**Comment by TheBronx** [comment]
oops, you are right, again :P

**Comment by TheBronx** [comment]
is there anything wrong with this PR?

**Comment by barisusakli** [comment]
@TheBronx have you signed the CLA at https://www.clahub.com/agreements/NodeBB/NodeBB?

**Comment by psychobunny** [comment]
For more info @TheBronx (and sorry, one of the major reasons why we were delayed with merging this PR was due to getting the legal stuff out of the way first):

[Official Thread about CLA](https://community.nodebb.org/topic/3705/submitting-a-pull-request-to-nodebb-contributor-license-agreement)
[Sign CLA](https://www.clahub.com/agreements/NodeBB/NodeBB)

**Comment by TheBronx** [comment]
done

**Comment by MegaGM** [comment]
@TheBronx Good work! Sorry, but, please https://github.com/NodeBB/NodeBB/wiki/Plugin-Hooks

**Comment by TheBronx** [comment]
done @MegaGM

**Pull request merged**
