### PR TITLE
Replace bootswatch cdn from latest to 3.3.7

### PR DESCRIPTION
**Pull request by RoPP**
latest themes are for bootstap 4

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Pull requests need to be made against either `master` or `develop`. It looks like this pull request was made against a version branch and should not be merged. Please comment if you feel that this is in error.

Thanks!

**Comment by phit** [comment]
also needs to be changed here

https://github.com/NodeBB/NodeBB/blob/992e3128bdb7772b1bdc10e2cf746b0bf6d593db/public/src/client/account/settings.js#L58

**Comment by TheBronx** [comment]
I know it is closed, but in case anyone else is facing this problem:
I also had to edit a value in the database:
Find the **object "config"** and edit the **property "theme:src"**.
If you are using mongodb you can find the object with:
```
db.getCollection('objects').find({
    "_key": "config"
})
```
Just replace "latest" with "3.3.7" on property "theme:src".

Wasted quite some time trying to figure out why the code changes were not working... Hope it helps.

**Comment by julianlam** [comment]
Thanks @TheBronx! I'm sure this will help out others who have a custom skin saved

**Pull request closed without merging**
