### PR TITLE
Add basic eslint rules and apply them to code

### PR DESCRIPTION
**Pull request by HeeL**
Some basic eslint rules to keep code more consistent and follow common patterns defined in  [Node BB code style guide](https://docs.nodebb.org/en/latest/contributing/style-guide.html#code-formatting).

Eslint rules of NodeBB are extending google eslint rules. Some fixes that were easy to apply are now part of this pul request. The rest of restrictions were disabled and will be fixed in future pull requests. The list of disabled rules are listed in `.eslintrc` : 
```js
        "one-var": "off",
        "no-undef": "off",
        "max-len": "off",
        "no-new": "off",
        "max-nested-callbacks": "off",
        "no-mixed-requires": "off",
        "brace-style": "off",
        "max-statements-per-line": "off",
        "no-unused-vars": "off",
        "no-mixed-spaces-and-tabs": "off",
        "no-useless-concat": "off",
        "no-mixed-requires": "off",
        "require-jsdoc": "off",
        "eqeqeq": "off",
        "camelcase": "off",
        "no-negated-condition": "off",
        "no-negated-condition": "off",
        "wrap-iife": "off",
        "one-var-declaration-per-line": "off",
        "new-cap": "off",
        "no-lonely-if": "off",
        "radix": "off",
        "no-else-return": "off",
        "no-useless-escape": "off",
        "block-scoped-var": "off",
        "operator-assignment": "off",
        "default-case": "off",
        "yoda": "off",
        "no-use-before-define": "off",
        "no-loop-func": "off",
        "no-void": "off",
        "valid-jsdoc": "off",
        "o-eq-null": "off",
        "no-cond-assign": "off",
        "no-eq-null": "off",
        "no-redeclare": "off",
        "no-unreachable": "off",
        "no-nested-ternary": "off",
        "operator-linebreak": "off",
        "guard-for-in": "off",
        "no-unneeded-ternary": "off",
        "no-sequences": "off",
        "no-extend-native": "off",
        "no-shadow-restricted-names": "off",
        "no-extra-boolean-cast": "off",
        "no-undef-init": "off",
        "no-script-url": "off",
        "no-path-concat": "off",
        "no-unused-expressions": "off",
        "no-restricted-module": "off",
        "no-return-assign": "off",
        "no-restricted-modules": "off"
```

### CODE REVIEW

**Comment by HeeL** [comment]
Will that be merged if I fix the conflicts?

**Comment by julianlam** [comment]
First off, I appreciate the work you put in! Looks like in addition to the rules, you fixes the errors in NodeBB itself?

As someone running for president may say... **TREMENDOUS**!

However, can you apply these rules one by one (with the associated fixes in the code)?

Because...

1. Fewer files changes per PR means they will become stale less quickly
2. Fewer files means a each PR is more easily digestable
3. It will mean my browser won't lock up whenever I press "Files Changed" at the top :trollface:

**Comment by julianlam** [comment]
Oh, and... if you wanted a fourth reason... if you break it up into multiple commits, after 4 of them are made, you get [a free t-shirt from DigitalOcean](https://hacktoberfest.digitalocean.com/)!

**Comment by pitaj** [comment]
Also, I'd suggest switching to `eslint-config-airbnb` instead of Google. It's more comprehensive and also supports ES6 explicitly.

**Comment by HeeL** [comment]
@julianlam, ok, the argument with the t-shirt sounds very reasonable :)

1. Will you prefer to have a separate PR for each rule?
2. I've seen you liked the idea to use AirBnb eslint rules, even though in docs it says that you are mostly following Google style guide. Should I extend Airbnb rules instead?

**Comment by julianlam** [comment]
Yes, separate pull requests for groups of related rules would be ideal... and stagger them out, nobody wants to review 100 pull requests over Thanksgiving weekend :laughing:

**Comment by pitaj** [comment]
@HeeL 

> Should I extend Airbnb rules instead?

Yes.

**Comment by HeeL** [comment]
This PR can be closed in favour of PR with Airbnb rules #5100  and all the following PRs that will introduce fixes to the rules

**Pull request closed without merging**
