### PR TITLE
Remove external sources from installer page

### LINKED ISSUE #6098: NodeBB requires external CDN resources for installer to work [reliability & security nitpick]
NodeBB as deployed via the docker image appears to require external resources from maxcdn.bootstrapcdn.com, fonts.googleapis.com and code.jquery.com to work. This is not a good thing because it makes a NodeBB instance rely on external CDN providers the forum admin might not even be aware of, and it requires a more unsafe custom CSP to allow those resources to load. It'd be better if those could somehow packaged with NodeBB on deployment (especially since the versions appear to be pinned anyway).

- **NodeBB version:** the docker container launch log doesn't say, so I don't know
- **NodeBB git hash:** no idea, but nodebb/docker hash is sha256:d7fc601bcfff2a6e52a846a2a37b426509b3ccfba27035b27b9c36f76bb244d8
- **Database type:** mongo or redis
- **Database version:** 4.0.2

- **Exact steps to cause this issue:**
1. Launch nodebb/docker from DockerHub
2. Browse to installer with proxy that inserts CSP without unsafe-inline
3. See broken design and errors in the browser console
- **What you expected:**
works without custom external allowed script hosts in CSP, no access to external CDNs
- **What happened instead:**
requires external CDN access combined with CSP entries for those hosts

Edit: updated the issue text now that I know what the issue is

### PR DESCRIPTION
**Pull request by pitaj**
Closes #6098

### CODE REVIEW

**Comment by julianlam** [comment]
The asterisk itself drifts in a circle :grimacing: 

selection_139

**Comment by julianlam** [comment]
Also this change seems to dump `bootstrap.min.css` into `public` :\

**Comment by pitaj** [comment]
> The asterisk itself drifts in a circle 😬

What browser? It shouldn't be italic either. I can't reproduce that. 

> Not possible to use FA?

I wanted to minimize the use of external resources, and replacing the enormous fontawesome inclusion with a rotating asterisk that's only used _twice_ seemed like a good way to do so.

> Also this change seems to dump `bootstrap.min.css` into public :\

It should be deleted on launch along with `installer.css` and `installer.min.js`

**Comment by julianlam** [comment]
> What browser? It shouldn't be italic either. I can't reproduce that.

FF, which may have its own... intricacies, of course. It _does_ spin properly, I'm just saying that the spinning artifact itself drifts in a circle :smile: 

Perfectly fine with your rationale to replace FA with this CSS :+1: worthy compromise in my opinion.

**Comment by JonasT** [comment]
I just tested this pull request in the latest revision in docker and it works fine! <3

**Pull request merged**
