### PR TITLE
fix reload actions

### PR DESCRIPTION
**Pull request by yariplus**
button functions were backwards
fixed some grammar
made theme changes use toaster alerts

### CODE REVIEW

**Comment by yariplus** [comment]
fixes #6395

**Comment by yariplus** [comment]
Better option would be to discretely call hide instead of using a timeout.

**Comment by pitaj** [comment]
Yeah I was thinking just don't timeout, wait for the restart signal to come in.

**Comment by julianlam** [comment]
@yariplus have you tested your code with @pitaj's updated alert code with `alert_id`s and whatnot?

**Comment by yariplus** [comment]
@julianlam indeed

**Pull request merged**
