### PR TITLE
Build refactor

### PR DESCRIPTION
**Pull request by pitaj**
- Target aliases and bundles
- More concurrency
- Use `--series` to force series processing
- Minifier self-hosted threading
- meta/css delegates to minifier

### CODE REVIEW

**Comment by julianlam** [comment]
Do you have benchmarks showing build times between yours and the existing system?

Need to know rationale for a rewrite of this code as it would mean the build system becomes a black box. Is it easier to swap out minifiers, etc?

**Comment by pichalite** [comment]
@julianlam pitaj's gonna give you some random numbers saying it's waaaay better :trollface:

**Comment by pitaj** [comment]
I'd suggest looking at the [whitespace-ignored diff](https://github.com/NodeBB/NodeBB/pull/5664/files?w=1), since there were a lot of indentation changes. It makes it easier to see the actual changes.

The refactor of `meta/build` is, IMO, similar to the refactor of `./nodebb upgrade`. It removes the necessity for log statements in each method. It organizes and standardizes the individual methods to allow for easier extension and maintenance. It also allows for aliases and splitting up the individual JS methods to be run one at a time or altogether.

The `meta/minifier`, `meta/js`, and `meta/css` changes were all made to allow for easier extension of the minifier, and allowed for moving the css minification to the minifier, and hopefully allows for moving the module minification to a forked thread as well. It centralizes the minification, and abstracts away the forking error handling and everything out of the other modules.

There were some other `meta/css` tweaks to allow for more asynchronicity by removing synchronous `fs` method usage which required rewriting some of the async logic. 

Here are some benchmarks (10 runs each) [seconds]:

| old unminified | new unminified | old minified | new minified |
| ---------------- | ----------------- | ------------- | -------------- |
| 5.92                 | 4.32                    | 11.13           | 6.94               |
|                         | -27%                  |                     | -38%             |

As you can see, the new ones are significantly faster. I can provide the full timing sets if you want.

**Comment by julianlam** [comment]
:shipit:

**Pull request merged**
