### PR TITLE
Standard language codes

### PR DESCRIPTION
**Pull request by pitaj**
Provides a fallback for plugins that use the old codes.
Also changes route for fetching translation namespaces to something a little more fitting.

### CODE REVIEW

**Comment by nodebb-misty** [comment]
Hello there! :smile:

Our internationalisation project is handled through [our Transifex project](https://www.transifex.com/projects/p/nodebb/). Unfortunately, we cannot accept changes to language files directly via pull request as it would then become out-of-sync with the translations hosted there.

Please re-apply your changes via the Transifex website, and they will be pulled in periodically. If you require the translations sooner, please ping a project maintainer and they can manually pull the translations sooner.

Thank you! :angel:

----

*This is an automated message. If you feel this action was in error, please comment on this pull request so it can be looked at again*

**Comment by pitaj** [comment]
One notable change: this causes the prefetches set up in the default composer to error out due to both the incorrect route and the incorrect language code format.

**Comment by julianlam** [comment]
:laughing: misty...

**Comment by julianlam** [comment]
Waiting on @pitaj to fix `RELATIVE_PATH` issue before testing...

**Comment by julianlam** [comment]
Post merge:
* Delete `pitaj-standard-lang-codes` branch in GitHub remote

**Pull request merged**
