### PR TITLE
Added volatile counters to Analytics (issue #6569)

### PR DESCRIPTION
**Pull request by Dravere**
Since it is so easy to implement, I decided to go forward and just propose a pull request for issue #6569 :smile:

### CODE REVIEW

**Comment by julianlam** [comment]
The only thing that I am worried about here is that it could be removed in a future code review because it doesn't look like the getters are used anywhere in the codebase.

Would a hook-based approach work better? That is, firing off an action hook whenever a value is incremented.

**Comment by Dravere** [comment]
I wouldn't say that it would work better, but it would work as well. The thing is, for example with Prometheus it scraps metrics in a configured interval like all 15 seconds. I would have simply grabbed the latest value then. The hook would basically be a bit less efficient but probably negligible.

So instead of having the volatile counter you would say I just put in a `plugins.fireHook('action:analytics.increment', { key: key });` when the counter is incremented? This way it is possible to have the volatile counter in the plugin?

**Comment by julianlam** [comment]
> This way it is possible to have the volatile counter in the plugin?

Yes, that is correct. You'd then manage the counter in the plugin itself and push to prometheus when needed/called. The other alternative solution would be to have the **plugin** fire the hook, and have core listen for it, but that's a little backwards and potentially confusing as well :smile:

**Comment by julianlam** [comment]
Also unless I'm mistaken there's no code in this PR for actually resetting (flushing?) the contents of the volatile counter... so it'd always be increasing until the nodebb process restarts.

**Comment by Dravere** [comment]
It was the intention to let them only go up because that is what a counter is. It is also defined that way by Prometheus: https://prometheus.io/docs/concepts/metric_types/#counter

**Comment by julianlam** [comment]
@pitaj actually suggested a different approach (not to discount your work @Dravere :smile:)

Instead of an action hook to increment a counter in a plugin, we could fire a hook on NodeBB start that queries plugins for a listener function to execute on counter increment. Therefore instead of a plugin listening for the action hook (and incurring whatever overhead there is), NodeBB core would simply call the function reference passed back repeatedly.

The volatile counter itself would still be stored on the plugin side.

I'm good with either the action hook, or this alternative solution.

**Comment by julianlam** [comment]
@pitaj Looking back at this in the morning, passing a function reference is literally the same thing as what we do now with an action hook :thinking:

**Comment by Dravere** [comment]
@julianlam That is exactly what was my conclusion as well. It is basically a plugin system implemented on top of the plugin system. Sure it might have a bit less overhead but other than that there isn't much difference than the current plugin implementation.

It probably is a better idea to improve performance of the current plugin system than to introduce a new one only for this. I think in regards to code quality the solution #6575 proposed by @julianlam is still the best option.

**Comment by julianlam** [comment]
Closed in favour of #6575

**Pull request closed without merging**
