### PR TITLE
V0.9.x

### PR DESCRIPTION
**Pull request by Jdesk**

### CODE REVIEW

**Comment by Jdesk** [comment]
just want to keep up with you guys

**Comment by julianlam** [comment]
What's this PR for?

**Comment by Jdesk** [comment]
it was for a typo - a capital where a lowercase should have been used - i have to go through the code again so i can point it out - i should have left a more detailed message rather than generic.

**Comment by Jdesk** [comment]
also on a sidenote while we are chatting - the docker build doesn't line up - on your official repo - --name my-forum-redis initially then name -- dockerdevs to link. 

docker run --name my-forum-redis -d -p 6379:6379 nodebb/docker:centos-redis
docker run --name my-forum-redis -d -p 6379:6379 nodebb/docker:ubuntu-redis

docker run --name dockerdev-nodebb --link dockerdev-redis:redis -p 80:80 -p 443:443 -p 4567:4567 -P -t -i nodebb/docker:centos

docker run --name dockerdev-nodebb --link dockerdev-redis:redis -p 80:80 -p 443:443 -p 4567:4567 -P -t -i nodebb/docker:ubuntu

**Comment by Jdesk** [comment]
I'm not sure if your going through errors at all but when I run it - i get the wonderful does not exist error - i'm not sure what is off because i obviously change the names to match or to whatever i want - and it still won't build - on my end i have it passing on every ci test in the book with my automated build.  I also almost have a working bash script to deploy it - 

i just have a ton of work to get done - so i need to finish it before putting it up - i've tested it to the point of no return but it includes nginx config and phusion passenger so once the script is done running as long as dns is preconfigured the app will run on ./nodebb start or however you decide to start it up.

**Comment by julianlam** [comment]
Already fixed in 8304740bd58690da0209e419b584f0bd489989ba and backported to v0.9.x. Thanks though!

**Pull request closed without merging**
