### PR TITLE
fixes sitemap base url issue when using with subfolder

### PR DESCRIPTION
**Pull request by hb90dev**

### CODE REVIEW

**Comment by barisusakli** [comment]
I think you can just use `nconf.get('relative_path')` which would be `/forum` if installation is at `https://mysite.com/forum`.

**Comment by julianlam** [comment]
Yeah, `relative_path` should already be available globally, so you won't need to manually construct the prefix in every method :+1:

**Comment by hb90dev** [comment]
Great thanks !!

**Comment by julianlam** [comment]
@hb90dev No, you can get rid of `$prefix` altogether and just use `nconf.get('relative_path')` :smile:

**Comment by hb90dev** [comment]
Okay )))

**Pull request merged**
