### PR TITLE
fix: NodeBB#11482 thumbs Post Can not upload a thumbnail, only multip…

### PR DESCRIPTION
**Pull request by Veronikya**
…le uploads

### CODE REVIEW

**Comment by barisusakli** [comment]
@Veronikya thanks for this, can you remove this line https://github.com/NodeBB/NodeBB/blob/master/test/helpers/index.js#L124,
lets see if all tests pass without it. Since your code should handle objects and turn it into an array 🤔

**Comment by barisusakli** [comment]
Can get rid of the `/2` here as well https://github.com/NodeBB/NodeBB/blob/master/test/uploads.js#L90-L91 since we don't upload x2 files each time

**Comment by Veronikya** [comment]
assert.strictEqual(orphans.length, 1);   
It looks like this, the quantity does not match
:)

**Comment by barisusakli** [comment]
Lgtm will merge later today

**Pull request merged**
